//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActivitiesBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActivitiesBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="activityLoad" type="{https://www.railml.org/schemas/3.2}ActivityLoad" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="activityRollingStock" type="{https://www.railml.org/schemas/3.2}ActivityRollingStock" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="activityOther" type="{https://www.railml.org/schemas/3.2}ActivityOther" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivitiesBase", propOrder = {
    "activityLoad",
    "activityRollingStock",
    "activityOther"
})
@XmlSeeAlso({
    Activities.class,
    ExtendedActivities.class
})
public abstract class ActivitiesBase {

    protected List<ActivityLoad> activityLoad;
    protected List<ActivityRollingStock> activityRollingStock;
    protected List<ActivityOther> activityOther;

    /**
     * Gets the value of the activityLoad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the activityLoad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivityLoad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivityLoad }
     * 
     * 
     */
    public List<ActivityLoad> getActivityLoad() {
        if (activityLoad == null) {
            activityLoad = new ArrayList<ActivityLoad>();
        }
        return this.activityLoad;
    }

    /**
     * Gets the value of the activityRollingStock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the activityRollingStock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivityRollingStock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivityRollingStock }
     * 
     * 
     */
    public List<ActivityRollingStock> getActivityRollingStock() {
        if (activityRollingStock == null) {
            activityRollingStock = new ArrayList<ActivityRollingStock>();
        }
        return this.activityRollingStock;
    }

    /**
     * Gets the value of the activityOther property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the activityOther property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivityOther().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivityOther }
     * 
     * 
     */
    public List<ActivityOther> getActivityOther() {
        if (activityOther == null) {
            activityOther = new ArrayList<ActivityOther>();
        }
        return this.activityOther;
    }

}
