//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdditionalStopInfoBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalStopInfoBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="passengerTextInfos" type="{https://www.railml.org/schemas/3.2}PassengerTextInfoRefs" minOccurs="0"/&gt;
 *         &lt;element name="announcements" type="{https://www.railml.org/schemas/3.2}AnnouncementRefs" minOccurs="0"/&gt;
 *         &lt;element name="origin" type="{https://www.railml.org/schemas/3.2}OriginDestinationInfo" minOccurs="0"/&gt;
 *         &lt;element name="destination" type="{https://www.railml.org/schemas/3.2}OriginDestinationInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="bipRef" use="required" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalStopInfoBase", propOrder = {
    "passengerTextInfos",
    "announcements",
    "origin",
    "destination"
})
@XmlSeeAlso({
    AdditionalStopInfo.class,
    ExtendedAdditionalStopInfo.class
})
public class AdditionalStopInfoBase {

    protected PassengerTextInfoRefs passengerTextInfos;
    protected AnnouncementRefs announcements;
    protected OriginDestinationInfo origin;
    protected OriginDestinationInfo destination;
    @XmlAttribute(name = "bipRef", required = true)
    protected String bipRef;

    /**
     * Gets the value of the passengerTextInfos property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerTextInfoRefs }
     *     
     */
    public PassengerTextInfoRefs getPassengerTextInfos() {
        return passengerTextInfos;
    }

    /**
     * Sets the value of the passengerTextInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerTextInfoRefs }
     *     
     */
    public void setPassengerTextInfos(PassengerTextInfoRefs value) {
        this.passengerTextInfos = value;
    }

    /**
     * Gets the value of the announcements property.
     * 
     * @return
     *     possible object is
     *     {@link AnnouncementRefs }
     *     
     */
    public AnnouncementRefs getAnnouncements() {
        return announcements;
    }

    /**
     * Sets the value of the announcements property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnouncementRefs }
     *     
     */
    public void setAnnouncements(AnnouncementRefs value) {
        this.announcements = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link OriginDestinationInfo }
     *     
     */
    public OriginDestinationInfo getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginDestinationInfo }
     *     
     */
    public void setOrigin(OriginDestinationInfo value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link OriginDestinationInfo }
     *     
     */
    public OriginDestinationInfo getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginDestinationInfo }
     *     
     */
    public void setDestination(OriginDestinationInfo value) {
        this.destination = value;
    }

    /**
     * Gets the value of the bipRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBipRef() {
        return bipRef;
    }

    /**
     * Sets the value of the bipRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBipRef(String value) {
        this.bipRef = value;
    }

}
