//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import javax.xml.datatype.Duration;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseActivity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}tElementWithID"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="previousActivities" type="{https://www.railml.org/schemas/3.2}PreviousActivities" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="minDuration" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="trainActivityClassification" type="{https://www.railml.org/schemas/3.2}TrainActivityClassificationExt" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseActivity", propOrder = {
    "previousActivities"
})
@XmlSeeAlso({
    ActivityTrainReverse.class,
    OrderedActivity.class
})
public abstract class BaseActivity
    extends TElementWithID
{

    protected PreviousActivities previousActivities;
    @XmlAttribute(name = "minDuration")
    protected Duration minDuration;
    @XmlAttribute(name = "trainActivityClassification")
    protected String trainActivityClassification;

    /**
     * Gets the value of the previousActivities property.
     * 
     * @return
     *     possible object is
     *     {@link PreviousActivities }
     *     
     */
    public PreviousActivities getPreviousActivities() {
        return previousActivities;
    }

    /**
     * Sets the value of the previousActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviousActivities }
     *     
     */
    public void setPreviousActivities(PreviousActivities value) {
        this.previousActivities = value;
    }

    /**
     * Gets the value of the minDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMinDuration() {
        return minDuration;
    }

    /**
     * Sets the value of the minDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMinDuration(Duration value) {
        this.minDuration = value;
    }

    /**
     * Gets the value of the trainActivityClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainActivityClassification() {
        return trainActivityClassification;
    }

    /**
     * Sets the value of the trainActivityClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainActivityClassification(String value) {
        this.trainActivityClassification = value;
    }

}
