//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancellationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancellationInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="announcements" type="{https://www.railml.org/schemas/3.2}AnnouncementRefs" minOccurs="0"/&gt;
 *         &lt;element name="passengerTextInfos" type="{https://www.railml.org/schemas/3.2}PassengerTextInfoRefs" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="reasonDescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cancelledByRef" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;attribute name="reason" type="{https://www.railml.org/schemas/3.2}InterruptionReasonExt" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancellationInfo", propOrder = {
    "announcements",
    "passengerTextInfos"
})
public class CancellationInfo {

    protected AnnouncementRefs announcements;
    protected PassengerTextInfoRefs passengerTextInfos;
    @XmlAttribute(name = "reasonDescription")
    protected String reasonDescription;
    @XmlAttribute(name = "cancelledByRef")
    protected String cancelledByRef;
    @XmlAttribute(name = "reason")
    protected String reason;

    /**
     * Gets the value of the announcements property.
     * 
     * @return
     *     possible object is
     *     {@link AnnouncementRefs }
     *     
     */
    public AnnouncementRefs getAnnouncements() {
        return announcements;
    }

    /**
     * Sets the value of the announcements property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnouncementRefs }
     *     
     */
    public void setAnnouncements(AnnouncementRefs value) {
        this.announcements = value;
    }

    /**
     * Gets the value of the passengerTextInfos property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerTextInfoRefs }
     *     
     */
    public PassengerTextInfoRefs getPassengerTextInfos() {
        return passengerTextInfos;
    }

    /**
     * Sets the value of the passengerTextInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerTextInfoRefs }
     *     
     */
    public void setPassengerTextInfos(PassengerTextInfoRefs value) {
        this.passengerTextInfos = value;
    }

    /**
     * Gets the value of the reasonDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonDescription() {
        return reasonDescription;
    }

    /**
     * Sets the value of the reasonDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonDescription(String value) {
        this.reasonDescription = value;
    }

    /**
     * Gets the value of the cancelledByRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelledByRef() {
        return cancelledByRef;
    }

    /**
     * Sets the value of the cancelledByRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelledByRef(String value) {
        this.cancelledByRef = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

}
