//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DerailerIS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DerailerIS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="derailSide" type="{https://www.railml.org/schemas/3.2}tSide" /&gt;
 *       &lt;attribute name="type" type="{https://www.railml.org/schemas/3.2}tDerailerType" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DerailerIS")
public class DerailerIS
    extends FunctionalInfrastructureEntity
{

    @XmlAttribute(name = "derailSide")
    protected TSide derailSide;
    @XmlAttribute(name = "type")
    protected TDerailerType type;

    /**
     * Gets the value of the derailSide property.
     * 
     * @return
     *     possible object is
     *     {@link TSide }
     *     
     */
    public TSide getDerailSide() {
        return derailSide;
    }

    /**
     * Sets the value of the derailSide property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSide }
     *     
     */
    public void setDerailSide(TSide value) {
        this.derailSide = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TDerailerType }
     *     
     */
    public TDerailerType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDerailerType }
     *     
     */
    public void setType(TDerailerType value) {
        this.type = value;
    }

}
