//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import javax.xml.datatype.Duration;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistanceBasedCalculationRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistanceBasedCalculationRule"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="referenceDistanceMeters" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="supplement" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistanceBasedCalculationRule")
public class DistanceBasedCalculationRule {

    @XmlAttribute(name = "referenceDistanceMeters")
    protected Integer referenceDistanceMeters;
    @XmlAttribute(name = "supplement")
    protected Duration supplement;

    /**
     * Gets the value of the referenceDistanceMeters property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReferenceDistanceMeters() {
        return referenceDistanceMeters;
    }

    /**
     * Sets the value of the referenceDistanceMeters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReferenceDistanceMeters(Integer value) {
        this.referenceDistanceMeters = value;
    }

    /**
     * Gets the value of the supplement property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getSupplement() {
        return supplement;
    }

    /**
     * Sets the value of the supplement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setSupplement(Duration value) {
        this.supplement = value;
    }

}
