//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The details of a facility for freight use.
 * 
 * <p>Java class for FreightFacilities complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FreightFacilities"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="designator" type="{https://www.railml.org/schemas/3.2}Designator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="freightType" type="{https://www.railml.org/schemas/3.2}tFreightListExt" /&gt;
 *       &lt;attribute name="hasWeatherProtection" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="load" type="{https://www.railml.org/schemas/3.2}tWeightTons" /&gt;
 *       &lt;attribute name="loadArea" type="{https://www.railml.org/schemas/3.2}tAreaSquareM" /&gt;
 *       &lt;attribute name="loadVolume" type="{https://www.railml.org/schemas/3.2}tVolumeCubicM" /&gt;
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="loadAccess" type="{https://www.railml.org/schemas/3.2}tLoadAccessListExt" /&gt;
 *       &lt;attribute name="selfDischarge" type="{https://www.railml.org/schemas/3.2}tSelfDischargeListExt" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FreightFacilities", propOrder = {
    "designator"
})
public class FreightFacilities {

    protected List<Designator> designator;
    @XmlAttribute(name = "freightType")
    protected String freightType;
    @XmlAttribute(name = "hasWeatherProtection")
    protected Boolean hasWeatherProtection;
    @XmlAttribute(name = "load")
    protected BigDecimal load;
    @XmlAttribute(name = "loadArea")
    protected BigDecimal loadArea;
    @XmlAttribute(name = "loadVolume")
    protected BigDecimal loadVolume;
    @XmlAttribute(name = "count")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger count;
    @XmlAttribute(name = "loadAccess")
    protected String loadAccess;
    @XmlAttribute(name = "selfDischarge")
    protected String selfDischarge;

    /**
     * Gets the value of the designator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the designator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDesignator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Designator }
     * 
     * 
     */
    public List<Designator> getDesignator() {
        if (designator == null) {
            designator = new ArrayList<Designator>();
        }
        return this.designator;
    }

    /**
     * Gets the value of the freightType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightType() {
        return freightType;
    }

    /**
     * Sets the value of the freightType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightType(String value) {
        this.freightType = value;
    }

    /**
     * Gets the value of the hasWeatherProtection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasWeatherProtection() {
        return hasWeatherProtection;
    }

    /**
     * Sets the value of the hasWeatherProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasWeatherProtection(Boolean value) {
        this.hasWeatherProtection = value;
    }

    /**
     * Gets the value of the load property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoad() {
        return load;
    }

    /**
     * Sets the value of the load property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoad(BigDecimal value) {
        this.load = value;
    }

    /**
     * Gets the value of the loadArea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoadArea() {
        return loadArea;
    }

    /**
     * Sets the value of the loadArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoadArea(BigDecimal value) {
        this.loadArea = value;
    }

    /**
     * Gets the value of the loadVolume property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoadVolume() {
        return loadVolume;
    }

    /**
     * Sets the value of the loadVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoadVolume(BigDecimal value) {
        this.loadVolume = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the loadAccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadAccess() {
        return loadAccess;
    }

    /**
     * Sets the value of the loadAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadAccess(String value) {
        this.loadAccess = value;
    }

    /**
     * Gets the value of the selfDischarge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelfDischarge() {
        return selfDischarge;
    }

    /**
     * Sets the value of the selfDischarge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelfDischarge(String value) {
        this.selfDischarge = value;
    }

}
