//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetTravelPath complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetTravelPath"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="from" type="{https://www.railml.org/schemas/3.2}NetElementRef"/&gt;
 *         &lt;element name="via" type="{https://www.railml.org/schemas/3.2}NetElementRef"/&gt;
 *         &lt;element name="to" type="{https://www.railml.org/schemas/3.2}NetElementRef"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="directed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="distance" type="{https://www.railml.org/schemas/3.2}tLengthM" /&gt;
 *       &lt;attribute name="lengthRestriction" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="changesDirection" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="numberOfDirectionChanges" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="requiresShunting" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="crossesContraflowTraffic" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetTravelPath", propOrder = {
    "from",
    "via",
    "to"
})
public class NetTravelPath {

    @XmlElement(required = true)
    protected NetElementRef from;
    @XmlElement(required = true)
    protected NetElementRef via;
    @XmlElement(required = true)
    protected NetElementRef to;
    @XmlAttribute(name = "directed", required = true)
    protected boolean directed;
    @XmlAttribute(name = "distance")
    protected BigDecimal distance;
    @XmlAttribute(name = "lengthRestriction")
    protected Boolean lengthRestriction;
    @XmlAttribute(name = "changesDirection")
    protected Boolean changesDirection;
    @XmlAttribute(name = "numberOfDirectionChanges")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfDirectionChanges;
    @XmlAttribute(name = "requiresShunting")
    protected Boolean requiresShunting;
    @XmlAttribute(name = "crossesContraflowTraffic")
    protected Boolean crossesContraflowTraffic;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link NetElementRef }
     *     
     */
    public NetElementRef getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetElementRef }
     *     
     */
    public void setFrom(NetElementRef value) {
        this.from = value;
    }

    /**
     * Gets the value of the via property.
     * 
     * @return
     *     possible object is
     *     {@link NetElementRef }
     *     
     */
    public NetElementRef getVia() {
        return via;
    }

    /**
     * Sets the value of the via property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetElementRef }
     *     
     */
    public void setVia(NetElementRef value) {
        this.via = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link NetElementRef }
     *     
     */
    public NetElementRef getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetElementRef }
     *     
     */
    public void setTo(NetElementRef value) {
        this.to = value;
    }

    /**
     * Gets the value of the directed property.
     * 
     */
    public boolean isDirected() {
        return directed;
    }

    /**
     * Sets the value of the directed property.
     * 
     */
    public void setDirected(boolean value) {
        this.directed = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistance(BigDecimal value) {
        this.distance = value;
    }

    /**
     * Gets the value of the lengthRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLengthRestriction() {
        return lengthRestriction;
    }

    /**
     * Sets the value of the lengthRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLengthRestriction(Boolean value) {
        this.lengthRestriction = value;
    }

    /**
     * Gets the value of the changesDirection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChangesDirection() {
        return changesDirection;
    }

    /**
     * Sets the value of the changesDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangesDirection(Boolean value) {
        this.changesDirection = value;
    }

    /**
     * Gets the value of the numberOfDirectionChanges property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfDirectionChanges() {
        return numberOfDirectionChanges;
    }

    /**
     * Sets the value of the numberOfDirectionChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfDirectionChanges(BigInteger value) {
        this.numberOfDirectionChanges = value;
    }

    /**
     * Gets the value of the requiresShunting property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresShunting() {
        return requiresShunting;
    }

    /**
     * Sets the value of the requiresShunting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresShunting(Boolean value) {
        this.requiresShunting = value;
    }

    /**
     * Gets the value of the crossesContraflowTraffic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCrossesContraflowTraffic() {
        return crossesContraflowTraffic;
    }

    /**
     * Sets the value of the crossesContraflowTraffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCrossesContraflowTraffic(Boolean value) {
        this.crossesContraflowTraffic = value;
    }

}
