//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OriginDestinationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginDestinationInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mediaResources" type="{https://www.railml.org/schemas/3.2}MediaResources" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="locationRef" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginDestinationInfo", propOrder = {
    "mediaResources"
})
public class OriginDestinationInfo {

    protected MediaResources mediaResources;
    @XmlAttribute(name = "locationRef")
    protected String locationRef;

    /**
     * Gets the value of the mediaResources property.
     * 
     * @return
     *     possible object is
     *     {@link MediaResources }
     *     
     */
    public MediaResources getMediaResources() {
        return mediaResources;
    }

    /**
     * Sets the value of the mediaResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaResources }
     *     
     */
    public void setMediaResources(MediaResources value) {
        this.mediaResources = value;
    }

    /**
     * Gets the value of the locationRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationRef() {
        return locationRef;
    }

    /**
     * Sets the value of the locationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationRef(String value) {
        this.locationRef = value;
    }

}
