//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Interlocking specific features of the power supply
 * 
 * <p>Java class for PowerSupplyIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowerSupplyIL"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}SystemAsset"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hasModeIndicator" type="{https://www.railml.org/schemas/3.2}EntityILref" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="numberOfSimultaneousSwitchingActuators" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="signalVoltageMode" type="{https://www.railml.org/schemas/3.2}tSignalVoltageModes" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowerSupplyIL", propOrder = {
    "hasModeIndicator"
})
public class PowerSupplyIL
    extends SystemAsset
{

    protected EntityILref hasModeIndicator;
    @XmlAttribute(name = "numberOfSimultaneousSwitchingActuators")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfSimultaneousSwitchingActuators;
    @XmlAttribute(name = "signalVoltageMode")
    protected TSignalVoltageModes signalVoltageMode;

    /**
     * Gets the value of the hasModeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getHasModeIndicator() {
        return hasModeIndicator;
    }

    /**
     * Sets the value of the hasModeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setHasModeIndicator(EntityILref value) {
        this.hasModeIndicator = value;
    }

    /**
     * Gets the value of the numberOfSimultaneousSwitchingActuators property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfSimultaneousSwitchingActuators() {
        return numberOfSimultaneousSwitchingActuators;
    }

    /**
     * Sets the value of the numberOfSimultaneousSwitchingActuators property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfSimultaneousSwitchingActuators(BigInteger value) {
        this.numberOfSimultaneousSwitchingActuators = value;
    }

    /**
     * Gets the value of the signalVoltageMode property.
     * 
     * @return
     *     possible object is
     *     {@link TSignalVoltageModes }
     *     
     */
    public TSignalVoltageModes getSignalVoltageMode() {
        return signalVoltageMode;
    }

    /**
     * Sets the value of the signalVoltageMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSignalVoltageModes }
     *     
     */
    public void setSignalVoltageMode(TSignalVoltageModes value) {
        this.signalVoltageMode = value;
    }

}
