//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This is the top level element for the rollingstock model. It is for the description of physical characteristics of any rollingstock.
 * 
 * <p>Java class for Rollingstock complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rollingstock"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="vehicles" type="{https://www.railml.org/schemas/3.2}Vehicles" minOccurs="0"/&gt;
 *         &lt;element name="formations" type="{https://www.railml.org/schemas/3.2}Formations" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rollingstock", propOrder = {
    "vehicles",
    "formations"
})
public class Rollingstock {

    protected Vehicles vehicles;
    protected Formations formations;

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link Vehicles }
     *     
     */
    public Vehicles getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vehicles }
     *     
     */
    public void setVehicles(Vehicles value) {
        this.vehicles = value;
    }

    /**
     * Gets the value of the formations property.
     * 
     * @return
     *     possible object is
     *     {@link Formations }
     *     
     */
    public Formations getFormations() {
        return formations;
    }

    /**
     * Sets the value of the formations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Formations }
     *     
     */
    public void setFormations(Formations value) {
        this.formations = value;
    }

}
