//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A route relation states the conditions that must be fulfilled for a given signal to be open. Note that these relations may well be captured in a control table. Therefore, the use is optional.
 * 
 * <p>Java class for RouteRelation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteRelation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}RouteObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="requiredSwitchPosition" type="{https://www.railml.org/schemas/3.2}SwitchAndGivenPosition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredDerailerPosition" type="{https://www.railml.org/schemas/3.2}DerailerAndGivenPosition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredCrossingPosition" type="{https://www.railml.org/schemas/3.2}CrossingAndGivenPosition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredDetectorState" type="{https://www.railml.org/schemas/3.2}DetectorAndGivenState" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredSignalAspect" type="{https://www.railml.org/schemas/3.2}SignalAndGivenAspect" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredSectionState" type="{https://www.railml.org/schemas/3.2}SectionAndGivenVacancy" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredKeyLockState" type="{https://www.railml.org/schemas/3.2}LockAndGivenState" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredLevelCrossingState" type="{https://www.railml.org/schemas/3.2}LevelCrossingAndGivenState" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredTunnelGateState" type="{https://www.railml.org/schemas/3.2}TunnelGateAndGivenState" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteRelation", propOrder = {
    "requiredSwitchPosition",
    "requiredDerailerPosition",
    "requiredCrossingPosition",
    "requiredDetectorState",
    "requiredSignalAspect",
    "requiredSectionState",
    "requiredKeyLockState",
    "requiredLevelCrossingState",
    "requiredTunnelGateState"
})
public class RouteRelation
    extends RouteObject
{

    protected List<SwitchAndGivenPosition> requiredSwitchPosition;
    protected List<DerailerAndGivenPosition> requiredDerailerPosition;
    protected List<CrossingAndGivenPosition> requiredCrossingPosition;
    protected List<DetectorAndGivenState> requiredDetectorState;
    protected List<SignalAndGivenAspect> requiredSignalAspect;
    protected List<SectionAndGivenVacancy> requiredSectionState;
    protected List<LockAndGivenState> requiredKeyLockState;
    protected List<LevelCrossingAndGivenState> requiredLevelCrossingState;
    protected List<TunnelGateAndGivenState> requiredTunnelGateState;

    /**
     * Gets the value of the requiredSwitchPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredSwitchPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredSwitchPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SwitchAndGivenPosition }
     * 
     * 
     */
    public List<SwitchAndGivenPosition> getRequiredSwitchPosition() {
        if (requiredSwitchPosition == null) {
            requiredSwitchPosition = new ArrayList<SwitchAndGivenPosition>();
        }
        return this.requiredSwitchPosition;
    }

    /**
     * Gets the value of the requiredDerailerPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredDerailerPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredDerailerPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DerailerAndGivenPosition }
     * 
     * 
     */
    public List<DerailerAndGivenPosition> getRequiredDerailerPosition() {
        if (requiredDerailerPosition == null) {
            requiredDerailerPosition = new ArrayList<DerailerAndGivenPosition>();
        }
        return this.requiredDerailerPosition;
    }

    /**
     * Gets the value of the requiredCrossingPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredCrossingPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredCrossingPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CrossingAndGivenPosition }
     * 
     * 
     */
    public List<CrossingAndGivenPosition> getRequiredCrossingPosition() {
        if (requiredCrossingPosition == null) {
            requiredCrossingPosition = new ArrayList<CrossingAndGivenPosition>();
        }
        return this.requiredCrossingPosition;
    }

    /**
     * Gets the value of the requiredDetectorState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredDetectorState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredDetectorState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetectorAndGivenState }
     * 
     * 
     */
    public List<DetectorAndGivenState> getRequiredDetectorState() {
        if (requiredDetectorState == null) {
            requiredDetectorState = new ArrayList<DetectorAndGivenState>();
        }
        return this.requiredDetectorState;
    }

    /**
     * Gets the value of the requiredSignalAspect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredSignalAspect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredSignalAspect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignalAndGivenAspect }
     * 
     * 
     */
    public List<SignalAndGivenAspect> getRequiredSignalAspect() {
        if (requiredSignalAspect == null) {
            requiredSignalAspect = new ArrayList<SignalAndGivenAspect>();
        }
        return this.requiredSignalAspect;
    }

    /**
     * Gets the value of the requiredSectionState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredSectionState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredSectionState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SectionAndGivenVacancy }
     * 
     * 
     */
    public List<SectionAndGivenVacancy> getRequiredSectionState() {
        if (requiredSectionState == null) {
            requiredSectionState = new ArrayList<SectionAndGivenVacancy>();
        }
        return this.requiredSectionState;
    }

    /**
     * Gets the value of the requiredKeyLockState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredKeyLockState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredKeyLockState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LockAndGivenState }
     * 
     * 
     */
    public List<LockAndGivenState> getRequiredKeyLockState() {
        if (requiredKeyLockState == null) {
            requiredKeyLockState = new ArrayList<LockAndGivenState>();
        }
        return this.requiredKeyLockState;
    }

    /**
     * Gets the value of the requiredLevelCrossingState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredLevelCrossingState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredLevelCrossingState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LevelCrossingAndGivenState }
     * 
     * 
     */
    public List<LevelCrossingAndGivenState> getRequiredLevelCrossingState() {
        if (requiredLevelCrossingState == null) {
            requiredLevelCrossingState = new ArrayList<LevelCrossingAndGivenState>();
        }
        return this.requiredLevelCrossingState;
    }

    /**
     * Gets the value of the requiredTunnelGateState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the requiredTunnelGateState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredTunnelGateState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TunnelGateAndGivenState }
     * 
     * 
     */
    public List<TunnelGateAndGivenState> getRequiredTunnelGateState() {
        if (requiredTunnelGateState == null) {
            requiredTunnelGateState = new ArrayList<TunnelGateAndGivenState>();
        }
        return this.requiredTunnelGateState;
    }

}
