//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTM_LevelNetwork complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTM_LevelNetwork"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}RTM_BaseObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="networkResource" type="{https://www.railml.org/schemas/3.2}tElementWithIDref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="descriptionLevel" type="{https://www.railml.org/schemas/3.2}tDescriptionLevel" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTM_LevelNetwork", propOrder = {
    "networkResource"
})
public class RTMLevelNetwork
    extends RTMBaseObject
{

    protected List<TElementWithIDref> networkResource;
    @XmlAttribute(name = "descriptionLevel")
    protected TDescriptionLevel descriptionLevel;

    /**
     * Gets the value of the networkResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the networkResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TElementWithIDref }
     * 
     * 
     */
    public List<TElementWithIDref> getNetworkResource() {
        if (networkResource == null) {
            networkResource = new ArrayList<TElementWithIDref>();
        }
        return this.networkResource;
    }

    /**
     * Gets the value of the descriptionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link TDescriptionLevel }
     *     
     */
    public TDescriptionLevel getDescriptionLevel() {
        return descriptionLevel;
    }

    /**
     * Sets the value of the descriptionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDescriptionLevel }
     *     
     */
    public void setDescriptionLevel(TDescriptionLevel value) {
        this.descriptionLevel = value;
    }

}
