//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScreenPositioningSystem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScreenPositioningSystem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}RTM_PositioningSystem"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="pxX" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="pxY" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="pxZ" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScreenPositioningSystem")
public class ScreenPositioningSystem
    extends RTMPositioningSystem
{

    @XmlAttribute(name = "pxX", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pxX;
    @XmlAttribute(name = "pxY", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pxY;
    @XmlAttribute(name = "pxZ")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pxZ;

    /**
     * Gets the value of the pxX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPxX() {
        return pxX;
    }

    /**
     * Sets the value of the pxX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPxX(BigInteger value) {
        this.pxX = value;
    }

    /**
     * Gets the value of the pxY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPxY() {
        return pxY;
    }

    /**
     * Sets the value of the pxY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPxY(BigInteger value) {
        this.pxY = value;
    }

    /**
     * Gets the value of the pxZ property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPxZ() {
        return pxZ;
    }

    /**
     * Sets the value of the pxZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPxZ(BigInteger value) {
        this.pxZ = value;
    }

}
