//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignalConstruction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalConstruction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="height" type="{https://www.railml.org/schemas/3.2}tLengthM" /&gt;
 *       &lt;attribute name="positionAtTrack" type="{https://www.railml.org/schemas/3.2}tWiderTrackPosition" /&gt;
 *       &lt;attribute name="type" type="{https://www.railml.org/schemas/3.2}tSignalConstructionType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalConstruction")
public class SignalConstruction {

    @XmlAttribute(name = "height")
    protected BigDecimal height;
    @XmlAttribute(name = "positionAtTrack")
    protected TWiderTrackPosition positionAtTrack;
    @XmlAttribute(name = "type")
    protected TSignalConstructionType type;

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeight(BigDecimal value) {
        this.height = value;
    }

    /**
     * Gets the value of the positionAtTrack property.
     * 
     * @return
     *     possible object is
     *     {@link TWiderTrackPosition }
     *     
     */
    public TWiderTrackPosition getPositionAtTrack() {
        return positionAtTrack;
    }

    /**
     * Sets the value of the positionAtTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWiderTrackPosition }
     *     
     */
    public void setPositionAtTrack(TWiderTrackPosition value) {
        this.positionAtTrack = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TSignalConstructionType }
     *     
     */
    public TSignalConstructionType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSignalConstructionType }
     *     
     */
    public void setType(TSignalConstructionType value) {
        this.type = value;
    }

}
