//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignalMilepost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalMilepost"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}SignalX"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="refersToLine" type="{https://www.railml.org/schemas/3.2}tElementWithIDref" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="shownValue" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalMilepost", propOrder = {
    "refersToLine"
})
public class SignalMilepost
    extends SignalX
{

    protected TElementWithIDref refersToLine;
    @XmlAttribute(name = "shownValue")
    protected String shownValue;

    /**
     * Gets the value of the refersToLine property.
     * 
     * @return
     *     possible object is
     *     {@link TElementWithIDref }
     *     
     */
    public TElementWithIDref getRefersToLine() {
        return refersToLine;
    }

    /**
     * Sets the value of the refersToLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TElementWithIDref }
     *     
     */
    public void setRefersToLine(TElementWithIDref value) {
        this.refersToLine = value;
    }

    /**
     * Gets the value of the shownValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShownValue() {
        return shownValue;
    }

    /**
     * Sets the value of the shownValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShownValue(String value) {
        this.shownValue = value;
    }

}
