//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeedProfileLoad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeedProfileLoad"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="exceedsAxleLoad" type="{https://www.railml.org/schemas/3.2}tWeightTons" /&gt;
 *       &lt;attribute name="exceedsMeterLoad" type="{https://www.railml.org/schemas/3.2}tMeterloadTonsPerMeter" /&gt;
 *       &lt;attribute name="maxAxleLoad" type="{https://www.railml.org/schemas/3.2}tWeightTons" /&gt;
 *       &lt;attribute name="maxMeterLoad" type="{https://www.railml.org/schemas/3.2}tMeterloadTonsPerMeter" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedProfileLoad")
public class SpeedProfileLoad {

    @XmlAttribute(name = "exceedsAxleLoad")
    protected BigDecimal exceedsAxleLoad;
    @XmlAttribute(name = "exceedsMeterLoad")
    protected BigDecimal exceedsMeterLoad;
    @XmlAttribute(name = "maxAxleLoad")
    protected BigDecimal maxAxleLoad;
    @XmlAttribute(name = "maxMeterLoad")
    protected BigDecimal maxMeterLoad;

    /**
     * Gets the value of the exceedsAxleLoad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExceedsAxleLoad() {
        return exceedsAxleLoad;
    }

    /**
     * Sets the value of the exceedsAxleLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExceedsAxleLoad(BigDecimal value) {
        this.exceedsAxleLoad = value;
    }

    /**
     * Gets the value of the exceedsMeterLoad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExceedsMeterLoad() {
        return exceedsMeterLoad;
    }

    /**
     * Sets the value of the exceedsMeterLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExceedsMeterLoad(BigDecimal value) {
        this.exceedsMeterLoad = value;
    }

    /**
     * Gets the value of the maxAxleLoad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxAxleLoad() {
        return maxAxleLoad;
    }

    /**
     * Sets the value of the maxAxleLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxAxleLoad(BigDecimal value) {
        this.maxAxleLoad = value;
    }

    /**
     * Gets the value of the maxMeterLoad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxMeterLoad() {
        return maxMeterLoad;
    }

    /**
     * Sets the value of the maxMeterLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxMeterLoad(BigDecimal value) {
        this.maxMeterLoad = value;
    }

}
