//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Virtual logical object used for indication and commanding of station related groups or zones on HMI
 * 
 * <p>Java class for StationIndicator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StationIndicator"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}IndicatingObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="belongsToOperationalPoint" type="{https://www.railml.org/schemas/3.2}EntityILref" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="usedFor" use="required" type="{https://www.railml.org/schemas/3.2}tStationZonesListExt" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StationIndicator", propOrder = {
    "belongsToOperationalPoint"
})
public class StationIndicator
    extends IndicatingObject
{

    protected EntityILref belongsToOperationalPoint;
    @XmlAttribute(name = "usedFor", required = true)
    protected String usedFor;

    /**
     * Gets the value of the belongsToOperationalPoint property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getBelongsToOperationalPoint() {
        return belongsToOperationalPoint;
    }

    /**
     * Sets the value of the belongsToOperationalPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setBelongsToOperationalPoint(EntityILref value) {
        this.belongsToOperationalPoint = value;
    }

    /**
     * Gets the value of the usedFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsedFor() {
        return usedFor;
    }

    /**
     * Sets the value of the usedFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsedFor(String value) {
        this.usedFor = value;
    }

}
