//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * For some relations between movable elements restrictions apply concerning the combination of both elements positions.
 * 
 * <p>Java class for SwitchPositionRestriction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SwitchPositionRestriction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}BasicEntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="relatedSwitchInPosition" type="{https://www.railml.org/schemas/3.2}SwitchAndPosition" minOccurs="0"/&gt;
 *         &lt;element name="relatedDerailerInPosition" type="{https://www.railml.org/schemas/3.2}DerailerAndPosition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="restrictedPosition" use="required" type="{https://www.railml.org/schemas/3.2}tSwitchPosition" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SwitchPositionRestriction", propOrder = {
    "relatedSwitchInPosition",
    "relatedDerailerInPosition"
})
public class SwitchPositionRestriction
    extends BasicEntityIL
{

    protected SwitchAndPosition relatedSwitchInPosition;
    protected DerailerAndPosition relatedDerailerInPosition;
    @XmlAttribute(name = "restrictedPosition", required = true)
    protected TSwitchPosition restrictedPosition;

    /**
     * Gets the value of the relatedSwitchInPosition property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchAndPosition }
     *     
     */
    public SwitchAndPosition getRelatedSwitchInPosition() {
        return relatedSwitchInPosition;
    }

    /**
     * Sets the value of the relatedSwitchInPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchAndPosition }
     *     
     */
    public void setRelatedSwitchInPosition(SwitchAndPosition value) {
        this.relatedSwitchInPosition = value;
    }

    /**
     * Gets the value of the relatedDerailerInPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DerailerAndPosition }
     *     
     */
    public DerailerAndPosition getRelatedDerailerInPosition() {
        return relatedDerailerInPosition;
    }

    /**
     * Sets the value of the relatedDerailerInPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerailerAndPosition }
     *     
     */
    public void setRelatedDerailerInPosition(DerailerAndPosition value) {
        this.relatedDerailerInPosition = value;
    }

    /**
     * Gets the value of the restrictedPosition property.
     * 
     * @return
     *     possible object is
     *     {@link TSwitchPosition }
     *     
     */
    public TSwitchPosition getRestrictedPosition() {
        return restrictedPosition;
    }

    /**
     * Sets the value of the restrictedPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSwitchPosition }
     *     
     */
    public void setRestrictedPosition(TSwitchPosition value) {
        this.restrictedPosition = value;
    }

}
