//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tElementWithID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tElementWithID"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{https://www.railml.org/schemas/3.2}tID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tElementWithID")
@XmlSeeAlso({
    Common.class,
    TElementWithIDandCode.class,
    TimePeriod.class,
    ElectrificationSystem.class,
    BaseItinerary.class,
    BaseItineraryPoint.class,
    CommercialScheduling.class,
    CommercialTrainSection.class,
    CommercialTrainVariant.class,
    Itinerary.class,
    OperationalTrainSectionPart.class,
    OperationalTrainVariant.class,
    BaseActivity.class,
    EntityRSwithID.class,
    EntityRSwithIDandDesignator.class,
    TElementWithIDandDesignator.class,
    Infrastructure.class,
    TElementWithIDandName.class
})
public abstract class TElementWithID {

    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
