//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tElementProjectionSymbolOrientation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="tElementProjectionSymbolOrientation"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="down"/&gt;
 *     &lt;enumeration value="left"/&gt;
 *     &lt;enumeration value="right"/&gt;
 *     &lt;enumeration value="up"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tElementProjectionSymbolOrientation")
@XmlEnum
public enum TElementProjectionSymbolOrientation {


    /**
     * the icon or symbol is turned 180 degrees
     * 
     */
    @XmlEnumValue("down")
    DOWN("down"),

    /**
     * icon or symbol turned 90 degrees left
     * 
     */
    @XmlEnumValue("left")
    LEFT("left"),

    /**
     * icon or symbol turned 90 degrees right
     * 
     */
    @XmlEnumValue("right")
    RIGHT("right"),

    /**
     * standard orientation of icon or symbol
     * 
     */
    @XmlEnumValue("up")
    UP("up");
    private final String value;

    TElementProjectionSymbolOrientation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TElementProjectionSymbolOrientation fromValue(String v) {
        for (TElementProjectionSymbolOrientation c: TElementProjectionSymbolOrientation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
