//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrackBed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackBed"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{https://www.railml.org/schemas/3.2}aTrackbed"/&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackBed")
public class TrackBed
    extends FunctionalInfrastructureEntity
{

    @XmlAttribute(name = "ballastType")
    protected TBallastType ballastType;
    @XmlAttribute(name = "railType")
    protected String railType;
    @XmlAttribute(name = "sleepersType")
    protected TSleepersType sleepersType;
    @XmlAttribute(name = "jointsType")
    protected TJointsType jointsType;

    /**
     * Gets the value of the ballastType property.
     * 
     * @return
     *     possible object is
     *     {@link TBallastType }
     *     
     */
    public TBallastType getBallastType() {
        return ballastType;
    }

    /**
     * Sets the value of the ballastType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBallastType }
     *     
     */
    public void setBallastType(TBallastType value) {
        this.ballastType = value;
    }

    /**
     * Gets the value of the railType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRailType() {
        return railType;
    }

    /**
     * Sets the value of the railType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRailType(String value) {
        this.railType = value;
    }

    /**
     * Gets the value of the sleepersType property.
     * 
     * @return
     *     possible object is
     *     {@link TSleepersType }
     *     
     */
    public TSleepersType getSleepersType() {
        return sleepersType;
    }

    /**
     * Sets the value of the sleepersType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSleepersType }
     *     
     */
    public void setSleepersType(TSleepersType value) {
        this.sleepersType = value;
    }

    /**
     * Gets the value of the jointsType property.
     * 
     * @return
     *     possible object is
     *     {@link TJointsType }
     *     
     */
    public TJointsType getJointsType() {
        return jointsType;
    }

    /**
     * Sets the value of the jointsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TJointsType }
     *     
     */
    public void setJointsType(TJointsType value) {
        this.jointsType = value;
    }

}
