//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A train protection element is a device that is installed on or next to the railway track with the purpose to automatically stop the train in case of violation of signal aspects.
 * For ETCS based train protection systems, please use dedicated elements like balise and baliseGroup instead.
 * 
 * <p>Java class for TrainProtectionElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainProtectionElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{https://www.railml.org/schemas/3.2}aTrainProtection"/&gt;
 *       &lt;attribute name="basedOnTemplate" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainProtectionElement")
public class TrainProtectionElement
    extends FunctionalInfrastructureEntity
{

    @XmlAttribute(name = "basedOnTemplate")
    protected String basedOnTemplate;
    @XmlAttribute(name = "trainProtectionSystem")
    protected String trainProtectionSystem;
    @XmlAttribute(name = "medium")
    protected TTrainProtectionMedium medium;
    @XmlAttribute(name = "monitoring")
    protected TTrainProtectionMonitoring monitoring;

    /**
     * Gets the value of the basedOnTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasedOnTemplate() {
        return basedOnTemplate;
    }

    /**
     * Sets the value of the basedOnTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasedOnTemplate(String value) {
        this.basedOnTemplate = value;
    }

    /**
     * Gets the value of the trainProtectionSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainProtectionSystem() {
        return trainProtectionSystem;
    }

    /**
     * Sets the value of the trainProtectionSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainProtectionSystem(String value) {
        this.trainProtectionSystem = value;
    }

    /**
     * Gets the value of the medium property.
     * 
     * @return
     *     possible object is
     *     {@link TTrainProtectionMedium }
     *     
     */
    public TTrainProtectionMedium getMedium() {
        return medium;
    }

    /**
     * Sets the value of the medium property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrainProtectionMedium }
     *     
     */
    public void setMedium(TTrainProtectionMedium value) {
        this.medium = value;
    }

    /**
     * Gets the value of the monitoring property.
     * 
     * @return
     *     possible object is
     *     {@link TTrainProtectionMonitoring }
     *     
     */
    public TTrainProtectionMonitoring getMonitoring() {
        return monitoring;
    }

    /**
     * Sets the value of the monitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrainProtectionMonitoring }
     *     
     */
    public void setMonitoring(TTrainProtectionMonitoring value) {
        this.monitoring = value;
    }

}
