//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSignalFunctionList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="tSignalFunctionList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="barrage"/&gt;
 *     &lt;enumeration value="block"/&gt;
 *     &lt;enumeration value="blockInterface"/&gt;
 *     &lt;enumeration value="distant"/&gt;
 *     &lt;enumeration value="entry"/&gt;
 *     &lt;enumeration value="exit"/&gt;
 *     &lt;enumeration value="group"/&gt;
 *     &lt;enumeration value="intermediate"/&gt;
 *     &lt;enumeration value="intermediateStop"/&gt;
 *     &lt;enumeration value="junction"/&gt;
 *     &lt;enumeration value="lineInterface"/&gt;
 *     &lt;enumeration value="main"/&gt;
 *     &lt;enumeration value="main+shunting"/&gt;
 *     &lt;enumeration value="repeater"/&gt;
 *     &lt;enumeration value="shunting"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tSignalFunctionList")
@XmlEnum
public enum TSignalFunctionList {

    @XmlEnumValue("barrage")
    BARRAGE("barrage"),
    @XmlEnumValue("block")
    BLOCK("block"),
    @XmlEnumValue("blockInterface")
    BLOCK_INTERFACE("blockInterface"),
    @XmlEnumValue("distant")
    DISTANT("distant"),
    @XmlEnumValue("entry")
    ENTRY("entry"),
    @XmlEnumValue("exit")
    EXIT("exit"),
    @XmlEnumValue("group")
    GROUP("group"),
    @XmlEnumValue("intermediate")
    INTERMEDIATE("intermediate"),
    @XmlEnumValue("intermediateStop")
    INTERMEDIATE_STOP("intermediateStop"),
    @XmlEnumValue("junction")
    JUNCTION("junction"),
    @XmlEnumValue("lineInterface")
    LINE_INTERFACE("lineInterface"),
    @XmlEnumValue("main")
    MAIN("main"),
    @XmlEnumValue("main+shunting")
    MAIN_SHUNTING("main+shunting"),
    @XmlEnumValue("repeater")
    REPEATER("repeater"),
    @XmlEnumValue("shunting")
    SHUNTING("shunting");
    private final String value;

    TSignalFunctionList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TSignalFunctionList fromValue(String v) {
        for (TSignalFunctionList c: TSignalFunctionList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
