//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tStationZonesList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="tStationZonesList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="automaticRouteSetting"/&gt;
 *     &lt;enumeration value="automaticTrainRouting"/&gt;
 *     &lt;enumeration value="catenary"/&gt;
 *     &lt;enumeration value="doorAlarm"/&gt;
 *     &lt;enumeration value="emergencyStopGroup"/&gt;
 *     &lt;enumeration value="errors"/&gt;
 *     &lt;enumeration value="fireAlarm"/&gt;
 *     &lt;enumeration value="handCrank"/&gt;
 *     &lt;enumeration value="inhibitionCheck"/&gt;
 *     &lt;enumeration value="keylockIndicator"/&gt;
 *     &lt;enumeration value="operatingArea"/&gt;
 *     &lt;enumeration value="operatingGroup"/&gt;
 *     &lt;enumeration value="operatingMode"/&gt;
 *     &lt;enumeration value="overallOperatingMode"/&gt;
 *     &lt;enumeration value="powerSupplyMode"/&gt;
 *     &lt;enumeration value="switchHeating"/&gt;
 *     &lt;enumeration value="switchHeatingTemperatureSensor"/&gt;
 *     &lt;enumeration value="switchPositionIndicator"/&gt;
 *     &lt;enumeration value="switchStaggering"/&gt;
 *     &lt;enumeration value="temperatureAlarm"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tStationZonesList")
@XmlEnum
public enum TStationZonesList {

    @XmlEnumValue("automaticRouteSetting")
    AUTOMATIC_ROUTE_SETTING("automaticRouteSetting"),
    @XmlEnumValue("automaticTrainRouting")
    AUTOMATIC_TRAIN_ROUTING("automaticTrainRouting"),
    @XmlEnumValue("catenary")
    CATENARY("catenary"),
    @XmlEnumValue("doorAlarm")
    DOOR_ALARM("doorAlarm"),
    @XmlEnumValue("emergencyStopGroup")
    EMERGENCY_STOP_GROUP("emergencyStopGroup"),
    @XmlEnumValue("errors")
    ERRORS("errors"),
    @XmlEnumValue("fireAlarm")
    FIRE_ALARM("fireAlarm"),
    @XmlEnumValue("handCrank")
    HAND_CRANK("handCrank"),
    @XmlEnumValue("inhibitionCheck")
    INHIBITION_CHECK("inhibitionCheck"),
    @XmlEnumValue("keylockIndicator")
    KEYLOCK_INDICATOR("keylockIndicator"),
    @XmlEnumValue("operatingArea")
    OPERATING_AREA("operatingArea"),
    @XmlEnumValue("operatingGroup")
    OPERATING_GROUP("operatingGroup"),
    @XmlEnumValue("operatingMode")
    OPERATING_MODE("operatingMode"),
    @XmlEnumValue("overallOperatingMode")
    OVERALL_OPERATING_MODE("overallOperatingMode"),
    @XmlEnumValue("powerSupplyMode")
    POWER_SUPPLY_MODE("powerSupplyMode"),
    @XmlEnumValue("switchHeating")
    SWITCH_HEATING("switchHeating"),
    @XmlEnumValue("switchHeatingTemperatureSensor")
    SWITCH_HEATING_TEMPERATURE_SENSOR("switchHeatingTemperatureSensor"),
    @XmlEnumValue("switchPositionIndicator")
    SWITCH_POSITION_INDICATOR("switchPositionIndicator"),
    @XmlEnumValue("switchStaggering")
    SWITCH_STAGGERING("switchStaggering"),
    @XmlEnumValue("temperatureAlarm")
    TEMPERATURE_ALARM("temperatureAlarm");
    private final String value;

    TStationZonesList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TStationZonesList fromValue(String v) {
        for (TStationZonesList c: TStationZonesList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
