//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.Duration;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * One aspect relation has a) one master signal showing a given aspect b) one or more slaves showing a given aspect. The slave aspect depends on the master aspect. c) an optional overlap when the master aspect is at danger. The path from slave to master may contain switches. The switch positions are given in order to unequivocally determine the path.
 * 
 * <p>Java class for AspectRelation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AspectRelation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}EntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="masterAspect" type="{https://www.railml.org/schemas/3.2}SignalAndAspect" minOccurs="0"/&gt;
 *         &lt;element name="slaveAspect" type="{https://www.railml.org/schemas/3.2}SignalAndAspect" minOccurs="0"/&gt;
 *         &lt;element name="distantAspect" type="{https://www.railml.org/schemas/3.2}SignalAndAspect" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="signalsSpeedProfile" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="appliesToRoute" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="passingSpeed" type="{https://www.railml.org/schemas/3.2}tSpeedKmPerHour" /&gt;
 *       &lt;attribute name="expectingSpeed" type="{https://www.railml.org/schemas/3.2}tSpeedKmPerHour" /&gt;
 *       &lt;attribute name="endSectionTime" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AspectRelation", propOrder = {
    "masterAspect",
    "slaveAspect",
    "distantAspect",
    "signalsSpeedProfile",
    "appliesToRoute"
})
public class AspectRelation
    extends EntityIL
{

    protected SignalAndAspect masterAspect;
    protected SignalAndAspect slaveAspect;
    protected List<SignalAndAspect> distantAspect;
    protected List<EntityILref> signalsSpeedProfile;
    protected List<EntityILref> appliesToRoute;
    @XmlAttribute(name = "passingSpeed")
    protected BigDecimal passingSpeed;
    @XmlAttribute(name = "expectingSpeed")
    protected BigDecimal expectingSpeed;
    @XmlAttribute(name = "endSectionTime")
    protected Duration endSectionTime;

    /**
     * Gets the value of the masterAspect property.
     * 
     * @return
     *     possible object is
     *     {@link SignalAndAspect }
     *     
     */
    public SignalAndAspect getMasterAspect() {
        return masterAspect;
    }

    /**
     * Sets the value of the masterAspect property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalAndAspect }
     *     
     */
    public void setMasterAspect(SignalAndAspect value) {
        this.masterAspect = value;
    }

    /**
     * Gets the value of the slaveAspect property.
     * 
     * @return
     *     possible object is
     *     {@link SignalAndAspect }
     *     
     */
    public SignalAndAspect getSlaveAspect() {
        return slaveAspect;
    }

    /**
     * Sets the value of the slaveAspect property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalAndAspect }
     *     
     */
    public void setSlaveAspect(SignalAndAspect value) {
        this.slaveAspect = value;
    }

    /**
     * Gets the value of the distantAspect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the distantAspect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistantAspect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignalAndAspect }
     * 
     * 
     */
    public List<SignalAndAspect> getDistantAspect() {
        if (distantAspect == null) {
            distantAspect = new ArrayList<SignalAndAspect>();
        }
        return this.distantAspect;
    }

    /**
     * Gets the value of the signalsSpeedProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the signalsSpeedProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignalsSpeedProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getSignalsSpeedProfile() {
        if (signalsSpeedProfile == null) {
            signalsSpeedProfile = new ArrayList<EntityILref>();
        }
        return this.signalsSpeedProfile;
    }

    /**
     * Gets the value of the appliesToRoute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the appliesToRoute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppliesToRoute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getAppliesToRoute() {
        if (appliesToRoute == null) {
            appliesToRoute = new ArrayList<EntityILref>();
        }
        return this.appliesToRoute;
    }

    /**
     * Gets the value of the passingSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPassingSpeed() {
        return passingSpeed;
    }

    /**
     * Sets the value of the passingSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPassingSpeed(BigDecimal value) {
        this.passingSpeed = value;
    }

    /**
     * Gets the value of the expectingSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpectingSpeed() {
        return expectingSpeed;
    }

    /**
     * Sets the value of the expectingSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpectingSpeed(BigDecimal value) {
        this.expectingSpeed = value;
    }

    /**
     * Gets the value of the endSectionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getEndSectionTime() {
        return endSectionTime;
    }

    /**
     * Sets the value of the endSectionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setEndSectionTime(Duration value) {
        this.endSectionTime = value;
    }

}
