//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Commercial complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Commercial"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="onRequest" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="onOff" type="{https://www.railml.org/schemas/3.2}OnOff" default="both" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Commercial")
public class Commercial {

    @XmlAttribute(name = "onRequest")
    protected Boolean onRequest;
    @XmlAttribute(name = "onOff")
    protected OnOff onOff;

    /**
     * Gets the value of the onRequest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOnRequest() {
        if (onRequest == null) {
            return false;
        } else {
            return onRequest;
        }
    }

    /**
     * Sets the value of the onRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnRequest(Boolean value) {
        this.onRequest = value;
    }

    /**
     * Gets the value of the onOff property.
     * 
     * @return
     *     possible object is
     *     {@link OnOff }
     *     
     */
    public OnOff getOnOff() {
        if (onOff == null) {
            return OnOff.BOTH;
        } else {
            return onOff;
        }
    }

    /**
     * Sets the value of the onOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnOff }
     *     
     */
    public void setOnOff(OnOff value) {
        this.onOff = value;
    }

}
