//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommercialConnectionConnector complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommercialConnectionConnector"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="commercialTrainReference" type="{https://www.railml.org/schemas/3.2}CommercialTrainVariantReference"/&gt;
 *         &lt;element name="externalTrainReference" type="{https://www.railml.org/schemas/3.2}ExternalTrainReference"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommercialConnectionConnector", propOrder = {
    "commercialTrainReference",
    "externalTrainReference"
})
public class CommercialConnectionConnector {

    protected CommercialTrainVariantReference commercialTrainReference;
    protected ExternalTrainReference externalTrainReference;

    /**
     * Gets the value of the commercialTrainReference property.
     * 
     * @return
     *     possible object is
     *     {@link CommercialTrainVariantReference }
     *     
     */
    public CommercialTrainVariantReference getCommercialTrainReference() {
        return commercialTrainReference;
    }

    /**
     * Sets the value of the commercialTrainReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommercialTrainVariantReference }
     *     
     */
    public void setCommercialTrainReference(CommercialTrainVariantReference value) {
        this.commercialTrainReference = value;
    }

    /**
     * Gets the value of the externalTrainReference property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalTrainReference }
     *     
     */
    public ExternalTrainReference getExternalTrainReference() {
        return externalTrainReference;
    }

    /**
     * Sets the value of the externalTrainReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalTrainReference }
     *     
     */
    public void setExternalTrainReference(ExternalTrainReference value) {
        this.externalTrainReference = value;
    }

}
