//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommercialScheduling complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommercialScheduling"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}tElementWithID"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operationalRange" type="{https://www.railml.org/schemas/3.2}OperationalRange" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="start" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;attribute name="end" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;attribute name="sectionRef" use="required" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;attribute name="validityRef" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommercialScheduling", propOrder = {
    "operationalRange"
})
public class CommercialScheduling
    extends TElementWithID
{

    @XmlElement(required = true)
    protected List<OperationalRange> operationalRange;
    @XmlAttribute(name = "start")
    protected String start;
    @XmlAttribute(name = "end")
    protected String end;
    @XmlAttribute(name = "sectionRef", required = true)
    protected String sectionRef;
    @XmlAttribute(name = "validityRef")
    protected String validityRef;

    /**
     * Gets the value of the operationalRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the operationalRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationalRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationalRange }
     * 
     * 
     */
    public List<OperationalRange> getOperationalRange() {
        if (operationalRange == null) {
            operationalRange = new ArrayList<OperationalRange>();
        }
        return this.operationalRange;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnd(String value) {
        this.end = value;
    }

    /**
     * Gets the value of the sectionRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectionRef() {
        return sectionRef;
    }

    /**
     * Sets the value of the sectionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectionRef(String value) {
        this.sectionRef = value;
    }

    /**
     * Gets the value of the validityRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityRef() {
        return validityRef;
    }

    /**
     * Sets the value of the validityRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityRef(String value) {
        this.validityRef = value;
    }

}
