//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The ETCS level transition marks a point where ETCS level is being changed.
 * 
 * <p>Java class for EtcsLevelTransition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EtcsLevelTransition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence maxOccurs="unbounded"&gt;
 *         &lt;element name="switchToLevel" type="{https://www.railml.org/schemas/3.2}EtcsLevelTransitionDestination" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EtcsLevelTransition", propOrder = {
    "switchToLevel"
})
public class EtcsLevelTransition
    extends FunctionalInfrastructureEntity
{

    @XmlElement(required = true)
    protected List<EtcsLevelTransitionDestination> switchToLevel;

    /**
     * Gets the value of the switchToLevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the switchToLevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSwitchToLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EtcsLevelTransitionDestination }
     * 
     * 
     */
    public List<EtcsLevelTransitionDestination> getSwitchToLevel() {
        if (switchToLevel == null) {
            switchToLevel = new ArrayList<EtcsLevelTransitionDestination>();
        }
        return this.switchToLevel;
    }

}
