//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Used by TVD section reset strategy that the Infrastructure Manager regulates. E.g. reset by sweep allowed, manual reset allowed. Note that the IM can apply different reset strategies to sections. Absence of a strategy implies that reset is not possible.
 * 
 * <p>Java class for GenericResetStrategy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericResetStrategy"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}EntityIL"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="resetStrategy" use="required" type="{https://www.railml.org/schemas/3.2}tGenericResetStrategyList" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericResetStrategy")
public class GenericResetStrategy
    extends EntityIL
{

    @XmlAttribute(name = "resetStrategy", required = true)
    protected TGenericResetStrategyList resetStrategy;

    /**
     * Gets the value of the resetStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link TGenericResetStrategyList }
     *     
     */
    public TGenericResetStrategyList getResetStrategy() {
        return resetStrategy;
    }

    /**
     * Sets the value of the resetStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGenericResetStrategyList }
     *     
     */
    public void setResetStrategy(TGenericResetStrategyList value) {
        this.resetStrategy = value;
    }

}
