//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * virtual logical object used for indication of status on HMI
 * 
 * <p>Java class for IndicatingObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndicatingObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}EntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hasCommand" type="{https://www.railml.org/schemas/3.2}CodedEntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hasIndication" type="{https://www.railml.org/schemas/3.2}CodedEntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="elementNumber" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndicatingObject", propOrder = {
    "hasCommand",
    "hasIndication"
})
@XmlSeeAlso({
    RouteStatusIndicator.class,
    SignalIndicator.class,
    StationIndicator.class,
    TrainNumberField.class
})
public abstract class IndicatingObject
    extends EntityIL
{

    protected List<CodedEntityILref> hasCommand;
    protected List<CodedEntityILref> hasIndication;
    @XmlAttribute(name = "elementNumber")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger elementNumber;

    /**
     * Gets the value of the hasCommand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the hasCommand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasCommand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedEntityILref }
     * 
     * 
     */
    public List<CodedEntityILref> getHasCommand() {
        if (hasCommand == null) {
            hasCommand = new ArrayList<CodedEntityILref>();
        }
        return this.hasCommand;
    }

    /**
     * Gets the value of the hasIndication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the hasIndication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasIndication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedEntityILref }
     * 
     * 
     */
    public List<CodedEntityILref> getHasIndication() {
        if (hasIndication == null) {
            hasIndication = new ArrayList<CodedEntityILref>();
        }
        return this.hasIndication;
    }

    /**
     * Gets the value of the elementNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getElementNumber() {
        return elementNumber;
    }

    /**
     * Sets the value of the elementNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setElementNumber(BigInteger value) {
        this.elementNumber = value;
    }

}
