//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This is the description of the interface status in command and message direction which is assumed in start-up cases, i.e. when both sides of the system are just powered up.
 * 
 * <p>Java class for InitStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InitStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="comString" use="required" type="{https://www.railml.org/schemas/3.2}tBitPatternAny" /&gt;
 *       &lt;attribute name="messString" use="required" type="{https://www.railml.org/schemas/3.2}tBitPatternAny" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitStatus")
public class InitStatus {

    @XmlAttribute(name = "comString", required = true)
    protected String comString;
    @XmlAttribute(name = "messString", required = true)
    protected String messString;

    /**
     * Gets the value of the comString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComString() {
        return comString;
    }

    /**
     * Sets the value of the comString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComString(String value) {
        this.comString = value;
    }

    /**
     * Gets the value of the messString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessString() {
        return messString;
    }

    /**
     * Sets the value of the messString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessString(String value) {
        this.messString = value;
    }

}
