//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This is the top level element for the interlocking model. It is the home of several elements (classes) containing the particular aspects of the information.
 * 
 * <p>Java class for Interlocking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Interlocking"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="assetsForInterlockings" type="{https://www.railml.org/schemas/3.2}AssetsForInterlockings" minOccurs="0"/&gt;
 *         &lt;element name="controllers" type="{https://www.railml.org/schemas/3.2}Controllers" minOccurs="0"/&gt;
 *         &lt;element name="signalBoxes" type="{https://www.railml.org/schemas/3.2}SignalBoxes" minOccurs="0"/&gt;
 *         &lt;element name="radioBlockCentres" type="{https://www.railml.org/schemas/3.2}RadioBlockCentres" minOccurs="0"/&gt;
 *         &lt;element name="specificInfrastructureManagers" type="{https://www.railml.org/schemas/3.2}GenericInfrastructureManagers" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Interlocking", propOrder = {
    "assetsForInterlockings",
    "controllers",
    "signalBoxes",
    "radioBlockCentres",
    "specificInfrastructureManagers"
})
public class Interlocking {

    protected AssetsForInterlockings assetsForInterlockings;
    protected Controllers controllers;
    protected SignalBoxes signalBoxes;
    protected RadioBlockCentres radioBlockCentres;
    protected GenericInfrastructureManagers specificInfrastructureManagers;

    /**
     * Gets the value of the assetsForInterlockings property.
     * 
     * @return
     *     possible object is
     *     {@link AssetsForInterlockings }
     *     
     */
    public AssetsForInterlockings getAssetsForInterlockings() {
        return assetsForInterlockings;
    }

    /**
     * Sets the value of the assetsForInterlockings property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetsForInterlockings }
     *     
     */
    public void setAssetsForInterlockings(AssetsForInterlockings value) {
        this.assetsForInterlockings = value;
    }

    /**
     * Gets the value of the controllers property.
     * 
     * @return
     *     possible object is
     *     {@link Controllers }
     *     
     */
    public Controllers getControllers() {
        return controllers;
    }

    /**
     * Sets the value of the controllers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Controllers }
     *     
     */
    public void setControllers(Controllers value) {
        this.controllers = value;
    }

    /**
     * Gets the value of the signalBoxes property.
     * 
     * @return
     *     possible object is
     *     {@link SignalBoxes }
     *     
     */
    public SignalBoxes getSignalBoxes() {
        return signalBoxes;
    }

    /**
     * Sets the value of the signalBoxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalBoxes }
     *     
     */
    public void setSignalBoxes(SignalBoxes value) {
        this.signalBoxes = value;
    }

    /**
     * Gets the value of the radioBlockCentres property.
     * 
     * @return
     *     possible object is
     *     {@link RadioBlockCentres }
     *     
     */
    public RadioBlockCentres getRadioBlockCentres() {
        return radioBlockCentres;
    }

    /**
     * Sets the value of the radioBlockCentres property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadioBlockCentres }
     *     
     */
    public void setRadioBlockCentres(RadioBlockCentres value) {
        this.radioBlockCentres = value;
    }

    /**
     * Gets the value of the specificInfrastructureManagers property.
     * 
     * @return
     *     possible object is
     *     {@link GenericInfrastructureManagers }
     *     
     */
    public GenericInfrastructureManagers getSpecificInfrastructureManagers() {
        return specificInfrastructureManagers;
    }

    /**
     * Sets the value of the specificInfrastructureManagers property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericInfrastructureManagers }
     *     
     */
    public void setSpecificInfrastructureManagers(GenericInfrastructureManagers value) {
        this.specificInfrastructureManagers = value;
    }

}
