//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * reference to any level crossing and its state inside the restricted area required for use
 * 
 * <p>Java class for LevelCrossingInState complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LevelCrossingInState"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}EntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="givenState" type="{https://www.railml.org/schemas/3.2}LevelCrossingAndGivenState"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LevelCrossingInState", propOrder = {
    "givenState"
})
public class LevelCrossingInState
    extends EntityIL
{

    @XmlElement(required = true)
    protected LevelCrossingAndGivenState givenState;

    /**
     * Gets the value of the givenState property.
     * 
     * @return
     *     possible object is
     *     {@link LevelCrossingAndGivenState }
     *     
     */
    public LevelCrossingAndGivenState getGivenState() {
        return givenState;
    }

    /**
     * Sets the value of the givenState property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelCrossingAndGivenState }
     *     
     */
    public void setGivenState(LevelCrossingAndGivenState value) {
        this.givenState = value;
    }

}
