//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The level crossings have some basic features which can be specified independent of the particular manufacturer. Most important is the control type saying how the control relation between the interlocking and the level crossing is.
 * 
 * <p>Java class for LevelCrossingTypeList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LevelCrossingTypeList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}EntityIL"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="controlType" use="required" type="{https://www.railml.org/schemas/3.2}tLevelCrossingControlTypes" /&gt;
 *       &lt;attribute name="allowsLocalOperation" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="hasBarrier" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="hasTrafficWarning" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LevelCrossingTypeList")
public class LevelCrossingTypeList
    extends EntityIL
{

    @XmlAttribute(name = "controlType", required = true)
    protected TLevelCrossingControlTypes controlType;
    @XmlAttribute(name = "allowsLocalOperation")
    protected Boolean allowsLocalOperation;
    @XmlAttribute(name = "hasBarrier")
    protected Boolean hasBarrier;
    @XmlAttribute(name = "hasTrafficWarning")
    protected Boolean hasTrafficWarning;

    /**
     * Gets the value of the controlType property.
     * 
     * @return
     *     possible object is
     *     {@link TLevelCrossingControlTypes }
     *     
     */
    public TLevelCrossingControlTypes getControlType() {
        return controlType;
    }

    /**
     * Sets the value of the controlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLevelCrossingControlTypes }
     *     
     */
    public void setControlType(TLevelCrossingControlTypes value) {
        this.controlType = value;
    }

    /**
     * Gets the value of the allowsLocalOperation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowsLocalOperation() {
        return allowsLocalOperation;
    }

    /**
     * Sets the value of the allowsLocalOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowsLocalOperation(Boolean value) {
        this.allowsLocalOperation = value;
    }

    /**
     * Gets the value of the hasBarrier property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasBarrier() {
        return hasBarrier;
    }

    /**
     * Sets the value of the hasBarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasBarrier(Boolean value) {
        this.hasBarrier = value;
    }

    /**
     * Gets the value of the hasTrafficWarning property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasTrafficWarning() {
        return hasTrafficWarning;
    }

    /**
     * Sets the value of the hasTrafficWarning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasTrafficWarning(Boolean value) {
        this.hasTrafficWarning = value;
    }

}
