//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A line is a sequence of one or more line sections forming a route, which connects operational points and which may consist of several tracks used for regular railway operation.
 * 
 * <p>Java class for Line complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Line"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="beginsInOP" type="{https://www.railml.org/schemas/3.2}tElementWithIDref" minOccurs="0"/&gt;
 *         &lt;element name="endsInOP" type="{https://www.railml.org/schemas/3.2}tElementWithIDref" minOccurs="0"/&gt;
 *         &lt;element name="length" type="{https://www.railml.org/schemas/3.2}Length" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lineTrafficCode" type="{https://www.railml.org/schemas/3.2}LineTrafficCode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lineCombinedTransportCode" type="{https://www.railml.org/schemas/3.2}LineCombinedTransportCode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lineLayout" type="{https://www.railml.org/schemas/3.2}LineLayout" minOccurs="0"/&gt;
 *         &lt;element name="linePerformance" type="{https://www.railml.org/schemas/3.2}LinePerformance" minOccurs="0"/&gt;
 *         &lt;element name="lineOperation" type="{https://www.railml.org/schemas/3.2}LineOperation" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="infrastructureManagerRef" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;attribute name="lineCategory" type="{https://www.railml.org/schemas/3.2}tLineCategoryExt" /&gt;
 *       &lt;attribute name="lineType" type="{https://www.railml.org/schemas/3.2}tLineType" /&gt;
 *       &lt;attribute name="belongsToParent" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;attribute name="basedOnTemplate" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Line", propOrder = {
    "beginsInOP",
    "endsInOP",
    "length",
    "lineTrafficCode",
    "lineCombinedTransportCode",
    "lineLayout",
    "linePerformance",
    "lineOperation"
})
public class Line
    extends FunctionalInfrastructureEntity
{

    protected TElementWithIDref beginsInOP;
    protected TElementWithIDref endsInOP;
    protected List<Length> length;
    protected List<LineTrafficCode> lineTrafficCode;
    protected List<LineCombinedTransportCode> lineCombinedTransportCode;
    protected LineLayout lineLayout;
    protected LinePerformance linePerformance;
    protected LineOperation lineOperation;
    @XmlAttribute(name = "infrastructureManagerRef")
    protected String infrastructureManagerRef;
    @XmlAttribute(name = "lineCategory")
    protected String lineCategory;
    @XmlAttribute(name = "lineType")
    protected TLineType lineType;
    @XmlAttribute(name = "belongsToParent")
    protected String belongsToParent;
    @XmlAttribute(name = "basedOnTemplate")
    protected String basedOnTemplate;

    /**
     * Gets the value of the beginsInOP property.
     * 
     * @return
     *     possible object is
     *     {@link TElementWithIDref }
     *     
     */
    public TElementWithIDref getBeginsInOP() {
        return beginsInOP;
    }

    /**
     * Sets the value of the beginsInOP property.
     * 
     * @param value
     *     allowed object is
     *     {@link TElementWithIDref }
     *     
     */
    public void setBeginsInOP(TElementWithIDref value) {
        this.beginsInOP = value;
    }

    /**
     * Gets the value of the endsInOP property.
     * 
     * @return
     *     possible object is
     *     {@link TElementWithIDref }
     *     
     */
    public TElementWithIDref getEndsInOP() {
        return endsInOP;
    }

    /**
     * Sets the value of the endsInOP property.
     * 
     * @param value
     *     allowed object is
     *     {@link TElementWithIDref }
     *     
     */
    public void setEndsInOP(TElementWithIDref value) {
        this.endsInOP = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the length property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLength().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Length }
     * 
     * 
     */
    public List<Length> getLength() {
        if (length == null) {
            length = new ArrayList<Length>();
        }
        return this.length;
    }

    /**
     * Gets the value of the lineTrafficCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the lineTrafficCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineTrafficCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineTrafficCode }
     * 
     * 
     */
    public List<LineTrafficCode> getLineTrafficCode() {
        if (lineTrafficCode == null) {
            lineTrafficCode = new ArrayList<LineTrafficCode>();
        }
        return this.lineTrafficCode;
    }

    /**
     * Gets the value of the lineCombinedTransportCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the lineCombinedTransportCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineCombinedTransportCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineCombinedTransportCode }
     * 
     * 
     */
    public List<LineCombinedTransportCode> getLineCombinedTransportCode() {
        if (lineCombinedTransportCode == null) {
            lineCombinedTransportCode = new ArrayList<LineCombinedTransportCode>();
        }
        return this.lineCombinedTransportCode;
    }

    /**
     * Gets the value of the lineLayout property.
     * 
     * @return
     *     possible object is
     *     {@link LineLayout }
     *     
     */
    public LineLayout getLineLayout() {
        return lineLayout;
    }

    /**
     * Sets the value of the lineLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineLayout }
     *     
     */
    public void setLineLayout(LineLayout value) {
        this.lineLayout = value;
    }

    /**
     * Gets the value of the linePerformance property.
     * 
     * @return
     *     possible object is
     *     {@link LinePerformance }
     *     
     */
    public LinePerformance getLinePerformance() {
        return linePerformance;
    }

    /**
     * Sets the value of the linePerformance property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinePerformance }
     *     
     */
    public void setLinePerformance(LinePerformance value) {
        this.linePerformance = value;
    }

    /**
     * Gets the value of the lineOperation property.
     * 
     * @return
     *     possible object is
     *     {@link LineOperation }
     *     
     */
    public LineOperation getLineOperation() {
        return lineOperation;
    }

    /**
     * Sets the value of the lineOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineOperation }
     *     
     */
    public void setLineOperation(LineOperation value) {
        this.lineOperation = value;
    }

    /**
     * Gets the value of the infrastructureManagerRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfrastructureManagerRef() {
        return infrastructureManagerRef;
    }

    /**
     * Sets the value of the infrastructureManagerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfrastructureManagerRef(String value) {
        this.infrastructureManagerRef = value;
    }

    /**
     * Gets the value of the lineCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineCategory() {
        return lineCategory;
    }

    /**
     * Sets the value of the lineCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineCategory(String value) {
        this.lineCategory = value;
    }

    /**
     * Gets the value of the lineType property.
     * 
     * @return
     *     possible object is
     *     {@link TLineType }
     *     
     */
    public TLineType getLineType() {
        return lineType;
    }

    /**
     * Sets the value of the lineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLineType }
     *     
     */
    public void setLineType(TLineType value) {
        this.lineType = value;
    }

    /**
     * Gets the value of the belongsToParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelongsToParent() {
        return belongsToParent;
    }

    /**
     * Sets the value of the belongsToParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelongsToParent(String value) {
        this.belongsToParent = value;
    }

    /**
     * Gets the value of the basedOnTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasedOnTemplate() {
        return basedOnTemplate;
    }

    /**
     * Sets the value of the basedOnTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasedOnTemplate(String value) {
        this.basedOnTemplate = value;
    }

}
