//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.Duration;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Abstract element defining the attributes common to movable elements. The movable element refers to TrackAsset, thus creating a link to the IS namespace.
 * 
 * <p>Java class for MovableElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MovableElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}TrackAsset"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="refersTo" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="2"/&gt;
 *         &lt;element name="hasGaugeClearanceMarker" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="hasTvdSection" type="{https://www.railml.org/schemas/3.2}EntityILref" minOccurs="0"/&gt;
 *         &lt;element name="connectedToPowerSupply" type="{https://www.railml.org/schemas/3.2}EntityILref" minOccurs="0"/&gt;
 *         &lt;element name="relatedMovableElement" type="{https://www.railml.org/schemas/3.2}EntityILref" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="maxThrowTime" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="typicalThrowTime" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="returnsToPreferredPosition" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="isKeyLocked" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="numberOfBladeSwitchActuators" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="numberOfFrogSwitchActuators" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="localOperated" type="{https://www.railml.org/schemas/3.2}tLocalOperationListExt" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MovableElement", propOrder = {
    "refersTo",
    "hasGaugeClearanceMarker",
    "hasTvdSection",
    "connectedToPowerSupply",
    "relatedMovableElement"
})
@XmlSeeAlso({
    DerailerIL.class,
    MovableCrossing.class,
    SwitchIL.class
})
public abstract class MovableElement
    extends TrackAsset
{

    @XmlElement(required = true)
    protected List<EntityILref> refersTo;
    protected List<EntityILref> hasGaugeClearanceMarker;
    protected EntityILref hasTvdSection;
    protected EntityILref connectedToPowerSupply;
    protected EntityILref relatedMovableElement;
    @XmlAttribute(name = "maxThrowTime")
    protected Duration maxThrowTime;
    @XmlAttribute(name = "typicalThrowTime")
    protected Duration typicalThrowTime;
    @XmlAttribute(name = "returnsToPreferredPosition")
    protected Boolean returnsToPreferredPosition;
    @XmlAttribute(name = "isKeyLocked")
    protected Boolean isKeyLocked;
    @XmlAttribute(name = "numberOfBladeSwitchActuators")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfBladeSwitchActuators;
    @XmlAttribute(name = "numberOfFrogSwitchActuators")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfFrogSwitchActuators;
    @XmlAttribute(name = "localOperated")
    protected String localOperated;

    /**
     * Gets the value of the refersTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the refersTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefersTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getRefersTo() {
        if (refersTo == null) {
            refersTo = new ArrayList<EntityILref>();
        }
        return this.refersTo;
    }

    /**
     * Gets the value of the hasGaugeClearanceMarker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the hasGaugeClearanceMarker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasGaugeClearanceMarker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getHasGaugeClearanceMarker() {
        if (hasGaugeClearanceMarker == null) {
            hasGaugeClearanceMarker = new ArrayList<EntityILref>();
        }
        return this.hasGaugeClearanceMarker;
    }

    /**
     * Gets the value of the hasTvdSection property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getHasTvdSection() {
        return hasTvdSection;
    }

    /**
     * Sets the value of the hasTvdSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setHasTvdSection(EntityILref value) {
        this.hasTvdSection = value;
    }

    /**
     * Gets the value of the connectedToPowerSupply property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getConnectedToPowerSupply() {
        return connectedToPowerSupply;
    }

    /**
     * Sets the value of the connectedToPowerSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setConnectedToPowerSupply(EntityILref value) {
        this.connectedToPowerSupply = value;
    }

    /**
     * Gets the value of the relatedMovableElement property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getRelatedMovableElement() {
        return relatedMovableElement;
    }

    /**
     * Sets the value of the relatedMovableElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setRelatedMovableElement(EntityILref value) {
        this.relatedMovableElement = value;
    }

    /**
     * Gets the value of the maxThrowTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMaxThrowTime() {
        return maxThrowTime;
    }

    /**
     * Sets the value of the maxThrowTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMaxThrowTime(Duration value) {
        this.maxThrowTime = value;
    }

    /**
     * Gets the value of the typicalThrowTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTypicalThrowTime() {
        return typicalThrowTime;
    }

    /**
     * Sets the value of the typicalThrowTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTypicalThrowTime(Duration value) {
        this.typicalThrowTime = value;
    }

    /**
     * Gets the value of the returnsToPreferredPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnsToPreferredPosition() {
        return returnsToPreferredPosition;
    }

    /**
     * Sets the value of the returnsToPreferredPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnsToPreferredPosition(Boolean value) {
        this.returnsToPreferredPosition = value;
    }

    /**
     * Gets the value of the isKeyLocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsKeyLocked() {
        return isKeyLocked;
    }

    /**
     * Sets the value of the isKeyLocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsKeyLocked(Boolean value) {
        this.isKeyLocked = value;
    }

    /**
     * Gets the value of the numberOfBladeSwitchActuators property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBladeSwitchActuators() {
        return numberOfBladeSwitchActuators;
    }

    /**
     * Sets the value of the numberOfBladeSwitchActuators property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBladeSwitchActuators(BigInteger value) {
        this.numberOfBladeSwitchActuators = value;
    }

    /**
     * Gets the value of the numberOfFrogSwitchActuators property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfFrogSwitchActuators() {
        return numberOfFrogSwitchActuators;
    }

    /**
     * Sets the value of the numberOfFrogSwitchActuators property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfFrogSwitchActuators(BigInteger value) {
        this.numberOfFrogSwitchActuators = value;
    }

    /**
     * Gets the value of the localOperated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalOperated() {
        return localOperated;
    }

    /**
     * Sets the value of the localOperated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalOperated(String value) {
        this.localOperated = value;
    }

}
