//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationalConnection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationalConnection"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}ConnectionBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="feeder" type="{https://www.railml.org/schemas/3.2}OperationalConnectionFeeder"/&gt;
 *         &lt;element name="connector" type="{https://www.railml.org/schemas/3.2}OperationalConnectionConnector"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationalConnection", propOrder = {
    "feeder",
    "connector"
})
public class OperationalConnection
    extends ConnectionBase
{

    @XmlElement(required = true)
    protected OperationalConnectionFeeder feeder;
    @XmlElement(required = true)
    protected OperationalConnectionConnector connector;

    /**
     * Gets the value of the feeder property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalConnectionFeeder }
     *     
     */
    public OperationalConnectionFeeder getFeeder() {
        return feeder;
    }

    /**
     * Sets the value of the feeder property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalConnectionFeeder }
     *     
     */
    public void setFeeder(OperationalConnectionFeeder value) {
        this.feeder = value;
    }

    /**
     * Gets the value of the connector property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalConnectionConnector }
     *     
     */
    public OperationalConnectionConnector getConnector() {
        return connector;
    }

    /**
     * Sets the value of the connector property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalConnectionConnector }
     *     
     */
    public void setConnector(OperationalConnectionConnector value) {
        this.connector = value;
    }

}
