//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrganizationalUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganizationalUnit"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}tElementWithIDandName"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isInfrastructureManager" type="{https://www.railml.org/schemas/3.2}InfrastructureManager" minOccurs="0"/&gt;
 *         &lt;element name="isVehicleManufacturer" type="{https://www.railml.org/schemas/3.2}VehicleManufacturer" minOccurs="0"/&gt;
 *         &lt;element name="isVehicleOperator" type="{https://www.railml.org/schemas/3.2}VehicleOperator" minOccurs="0"/&gt;
 *         &lt;element name="isCustomer" type="{https://www.railml.org/schemas/3.2}Customer" minOccurs="0"/&gt;
 *         &lt;element name="isRailwayUndertaking" type="{https://www.railml.org/schemas/3.2}RailwayUndertaking" minOccurs="0"/&gt;
 *         &lt;element name="isOperationalUndertaking" type="{https://www.railml.org/schemas/3.2}OperationalUndertaking" minOccurs="0"/&gt;
 *         &lt;element name="isConcessionaire" type="{https://www.railml.org/schemas/3.2}Concessionaire" minOccurs="0"/&gt;
 *         &lt;element name="isContractor" type="{https://www.railml.org/schemas/3.2}Contractor" minOccurs="0"/&gt;
 *         &lt;element name="isVehicleOwner" type="{https://www.railml.org/schemas/3.2}VehicleOwner" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationalUnit", propOrder = {
    "isInfrastructureManager",
    "isVehicleManufacturer",
    "isVehicleOperator",
    "isCustomer",
    "isRailwayUndertaking",
    "isOperationalUndertaking",
    "isConcessionaire",
    "isContractor",
    "isVehicleOwner"
})
public class OrganizationalUnit
    extends TElementWithIDandName
{

    protected InfrastructureManager isInfrastructureManager;
    protected VehicleManufacturer isVehicleManufacturer;
    protected VehicleOperator isVehicleOperator;
    protected Customer isCustomer;
    protected RailwayUndertaking isRailwayUndertaking;
    protected OperationalUndertaking isOperationalUndertaking;
    protected Concessionaire isConcessionaire;
    protected Contractor isContractor;
    protected VehicleOwner isVehicleOwner;
    @XmlAttribute(name = "code")
    protected String code;

    /**
     * Gets the value of the isInfrastructureManager property.
     * 
     * @return
     *     possible object is
     *     {@link InfrastructureManager }
     *     
     */
    public InfrastructureManager getIsInfrastructureManager() {
        return isInfrastructureManager;
    }

    /**
     * Sets the value of the isInfrastructureManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfrastructureManager }
     *     
     */
    public void setIsInfrastructureManager(InfrastructureManager value) {
        this.isInfrastructureManager = value;
    }

    /**
     * Gets the value of the isVehicleManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleManufacturer }
     *     
     */
    public VehicleManufacturer getIsVehicleManufacturer() {
        return isVehicleManufacturer;
    }

    /**
     * Sets the value of the isVehicleManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleManufacturer }
     *     
     */
    public void setIsVehicleManufacturer(VehicleManufacturer value) {
        this.isVehicleManufacturer = value;
    }

    /**
     * Gets the value of the isVehicleOperator property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleOperator }
     *     
     */
    public VehicleOperator getIsVehicleOperator() {
        return isVehicleOperator;
    }

    /**
     * Sets the value of the isVehicleOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleOperator }
     *     
     */
    public void setIsVehicleOperator(VehicleOperator value) {
        this.isVehicleOperator = value;
    }

    /**
     * Gets the value of the isCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getIsCustomer() {
        return isCustomer;
    }

    /**
     * Sets the value of the isCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setIsCustomer(Customer value) {
        this.isCustomer = value;
    }

    /**
     * Gets the value of the isRailwayUndertaking property.
     * 
     * @return
     *     possible object is
     *     {@link RailwayUndertaking }
     *     
     */
    public RailwayUndertaking getIsRailwayUndertaking() {
        return isRailwayUndertaking;
    }

    /**
     * Sets the value of the isRailwayUndertaking property.
     * 
     * @param value
     *     allowed object is
     *     {@link RailwayUndertaking }
     *     
     */
    public void setIsRailwayUndertaking(RailwayUndertaking value) {
        this.isRailwayUndertaking = value;
    }

    /**
     * Gets the value of the isOperationalUndertaking property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalUndertaking }
     *     
     */
    public OperationalUndertaking getIsOperationalUndertaking() {
        return isOperationalUndertaking;
    }

    /**
     * Sets the value of the isOperationalUndertaking property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalUndertaking }
     *     
     */
    public void setIsOperationalUndertaking(OperationalUndertaking value) {
        this.isOperationalUndertaking = value;
    }

    /**
     * Gets the value of the isConcessionaire property.
     * 
     * @return
     *     possible object is
     *     {@link Concessionaire }
     *     
     */
    public Concessionaire getIsConcessionaire() {
        return isConcessionaire;
    }

    /**
     * Sets the value of the isConcessionaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link Concessionaire }
     *     
     */
    public void setIsConcessionaire(Concessionaire value) {
        this.isConcessionaire = value;
    }

    /**
     * Gets the value of the isContractor property.
     * 
     * @return
     *     possible object is
     *     {@link Contractor }
     *     
     */
    public Contractor getIsContractor() {
        return isContractor;
    }

    /**
     * Sets the value of the isContractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contractor }
     *     
     */
    public void setIsContractor(Contractor value) {
        this.isContractor = value;
    }

    /**
     * Gets the value of the isVehicleOwner property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleOwner }
     *     
     */
    public VehicleOwner getIsVehicleOwner() {
        return isVehicleOwner;
    }

    /**
     * Sets the value of the isVehicleOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleOwner }
     *     
     */
    public void setIsVehicleOwner(VehicleOwner value) {
        this.isVehicleOwner = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
