//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A restricted area inside a station which can be controlled from a different controller as the rest of the station
 * 
 * <p>Java class for PermissionZone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PermissionZone"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}TrackAsset"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="canBeControlledBy" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded"/&gt;
 *         &lt;element name="controlledElement" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="belongsToParent" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PermissionZone", propOrder = {
    "canBeControlledBy",
    "controlledElement"
})
public class PermissionZone
    extends TrackAsset
{

    @XmlElement(required = true)
    protected List<EntityILref> canBeControlledBy;
    protected List<EntityILref> controlledElement;
    @XmlAttribute(name = "belongsToParent")
    protected String belongsToParent;

    /**
     * Gets the value of the canBeControlledBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the canBeControlledBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanBeControlledBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getCanBeControlledBy() {
        if (canBeControlledBy == null) {
            canBeControlledBy = new ArrayList<EntityILref>();
        }
        return this.canBeControlledBy;
    }

    /**
     * Gets the value of the controlledElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the controlledElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControlledElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getControlledElement() {
        if (controlledElement == null) {
            controlledElement = new ArrayList<EntityILref>();
        }
        return this.controlledElement;
    }

    /**
     * Gets the value of the belongsToParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelongsToParent() {
        return belongsToParent;
    }

    /**
     * Sets the value of the belongsToParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelongsToParent(String value) {
        this.belongsToParent = value;
    }

}
