//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The characteristics of an individual radioBlockCentre element (RBC)
 * 
 * <p>Java class for RadioBlockCentre complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RadioBlockCentre"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}ComputerNode"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="etcsGeneralData" type="{https://www.railml.org/schemas/3.2}EtcsGeneralData" minOccurs="0"/&gt;
 *         &lt;element name="isLimitedByRadioBlockCentreBorder" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="containedTrackAssets" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hasCommand" type="{https://www.railml.org/schemas/3.2}CodedEntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hasIndication" type="{https://www.railml.org/schemas/3.2}CodedEntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="connectedSignalBox" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioBlockCentre", propOrder = {
    "etcsGeneralData",
    "isLimitedByRadioBlockCentreBorder",
    "containedTrackAssets",
    "hasCommand",
    "hasIndication",
    "connectedSignalBox"
})
public class RadioBlockCentre
    extends ComputerNode
{

    protected EtcsGeneralData etcsGeneralData;
    protected List<EntityILref> isLimitedByRadioBlockCentreBorder;
    protected List<EntityILref> containedTrackAssets;
    protected List<CodedEntityILref> hasCommand;
    protected List<CodedEntityILref> hasIndication;
    protected List<EntityILref> connectedSignalBox;

    /**
     * Gets the value of the etcsGeneralData property.
     * 
     * @return
     *     possible object is
     *     {@link EtcsGeneralData }
     *     
     */
    public EtcsGeneralData getEtcsGeneralData() {
        return etcsGeneralData;
    }

    /**
     * Sets the value of the etcsGeneralData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EtcsGeneralData }
     *     
     */
    public void setEtcsGeneralData(EtcsGeneralData value) {
        this.etcsGeneralData = value;
    }

    /**
     * Gets the value of the isLimitedByRadioBlockCentreBorder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the isLimitedByRadioBlockCentreBorder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsLimitedByRadioBlockCentreBorder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getIsLimitedByRadioBlockCentreBorder() {
        if (isLimitedByRadioBlockCentreBorder == null) {
            isLimitedByRadioBlockCentreBorder = new ArrayList<EntityILref>();
        }
        return this.isLimitedByRadioBlockCentreBorder;
    }

    /**
     * Gets the value of the containedTrackAssets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the containedTrackAssets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainedTrackAssets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getContainedTrackAssets() {
        if (containedTrackAssets == null) {
            containedTrackAssets = new ArrayList<EntityILref>();
        }
        return this.containedTrackAssets;
    }

    /**
     * Gets the value of the hasCommand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the hasCommand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasCommand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedEntityILref }
     * 
     * 
     */
    public List<CodedEntityILref> getHasCommand() {
        if (hasCommand == null) {
            hasCommand = new ArrayList<CodedEntityILref>();
        }
        return this.hasCommand;
    }

    /**
     * Gets the value of the hasIndication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the hasIndication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasIndication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedEntityILref }
     * 
     * 
     */
    public List<CodedEntityILref> getHasIndication() {
        if (hasIndication == null) {
            hasIndication = new ArrayList<CodedEntityILref>();
        }
        return this.hasIndication;
    }

    /**
     * Gets the value of the connectedSignalBox property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the connectedSignalBox property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectedSignalBox().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getConnectedSignalBox() {
        if (connectedSignalBox == null) {
            connectedSignalBox = new ArrayList<EntityILref>();
        }
        return this.connectedSignalBox;
    }

}
