//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.Duration;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A signal has an identity attribute, a reference to a signal or sign defined in the RTM scheme. A sign (or ETCS markerboard) indicating a speed change may well be modelled as a signal because the interlocking is likely to issue a different speed code at that sign
 * 
 * <p>Java class for SignalIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalIL"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}TrackAsset"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="refersTo" type="{https://www.railml.org/schemas/3.2}EntityILref" minOccurs="0"/&gt;
 *         &lt;element name="protectsBlockExit" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hasRepeater" type="{https://www.railml.org/schemas/3.2}RepeaterSignal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hasIndicator" type="{https://www.railml.org/schemas/3.2}EntityILref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="releaseSpeed" type="{https://www.railml.org/schemas/3.2}tSpeedKmPerHour" /&gt;
 *       &lt;attribute name="malfunctionSpeed" type="{https://www.railml.org/schemas/3.2}tSpeedKmPerHour" /&gt;
 *       &lt;attribute name="approachSpeed" type="{https://www.railml.org/schemas/3.2}tSpeedKmPerHour" /&gt;
 *       &lt;attribute name="passingSpeed" type="{https://www.railml.org/schemas/3.2}tSpeedKmPerHour" /&gt;
 *       &lt;attribute name="releaseDelay" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="function" type="{https://www.railml.org/schemas/3.2}tSignalFunctionListExt" /&gt;
 *       &lt;attribute name="isNotWired" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="callOnAspectTime" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="sightDistance" type="{https://www.railml.org/schemas/3.2}tLengthM" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalIL", propOrder = {
    "refersTo",
    "protectsBlockExit",
    "hasRepeater",
    "hasIndicator"
})
public class SignalIL
    extends TrackAsset
{

    protected EntityILref refersTo;
    protected List<EntityILref> protectsBlockExit;
    protected List<RepeaterSignal> hasRepeater;
    protected List<EntityILref> hasIndicator;
    @XmlAttribute(name = "releaseSpeed")
    protected BigDecimal releaseSpeed;
    @XmlAttribute(name = "malfunctionSpeed")
    protected BigDecimal malfunctionSpeed;
    @XmlAttribute(name = "approachSpeed")
    protected BigDecimal approachSpeed;
    @XmlAttribute(name = "passingSpeed")
    protected BigDecimal passingSpeed;
    @XmlAttribute(name = "releaseDelay")
    protected Duration releaseDelay;
    @XmlAttribute(name = "function")
    protected String function;
    @XmlAttribute(name = "isNotWired")
    protected Boolean isNotWired;
    @XmlAttribute(name = "callOnAspectTime")
    protected Duration callOnAspectTime;
    @XmlAttribute(name = "sightDistance")
    protected BigDecimal sightDistance;

    /**
     * Gets the value of the refersTo property.
     * 
     * @return
     *     possible object is
     *     {@link EntityILref }
     *     
     */
    public EntityILref getRefersTo() {
        return refersTo;
    }

    /**
     * Sets the value of the refersTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityILref }
     *     
     */
    public void setRefersTo(EntityILref value) {
        this.refersTo = value;
    }

    /**
     * Gets the value of the protectsBlockExit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the protectsBlockExit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProtectsBlockExit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getProtectsBlockExit() {
        if (protectsBlockExit == null) {
            protectsBlockExit = new ArrayList<EntityILref>();
        }
        return this.protectsBlockExit;
    }

    /**
     * Gets the value of the hasRepeater property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the hasRepeater property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasRepeater().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RepeaterSignal }
     * 
     * 
     */
    public List<RepeaterSignal> getHasRepeater() {
        if (hasRepeater == null) {
            hasRepeater = new ArrayList<RepeaterSignal>();
        }
        return this.hasRepeater;
    }

    /**
     * Gets the value of the hasIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the hasIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityILref }
     * 
     * 
     */
    public List<EntityILref> getHasIndicator() {
        if (hasIndicator == null) {
            hasIndicator = new ArrayList<EntityILref>();
        }
        return this.hasIndicator;
    }

    /**
     * Gets the value of the releaseSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReleaseSpeed() {
        return releaseSpeed;
    }

    /**
     * Sets the value of the releaseSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReleaseSpeed(BigDecimal value) {
        this.releaseSpeed = value;
    }

    /**
     * Gets the value of the malfunctionSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMalfunctionSpeed() {
        return malfunctionSpeed;
    }

    /**
     * Sets the value of the malfunctionSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMalfunctionSpeed(BigDecimal value) {
        this.malfunctionSpeed = value;
    }

    /**
     * Gets the value of the approachSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getApproachSpeed() {
        return approachSpeed;
    }

    /**
     * Sets the value of the approachSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setApproachSpeed(BigDecimal value) {
        this.approachSpeed = value;
    }

    /**
     * Gets the value of the passingSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPassingSpeed() {
        return passingSpeed;
    }

    /**
     * Sets the value of the passingSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPassingSpeed(BigDecimal value) {
        this.passingSpeed = value;
    }

    /**
     * Gets the value of the releaseDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getReleaseDelay() {
        return releaseDelay;
    }

    /**
     * Sets the value of the releaseDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setReleaseDelay(Duration value) {
        this.releaseDelay = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the isNotWired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsNotWired() {
        return isNotWired;
    }

    /**
     * Sets the value of the isNotWired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsNotWired(Boolean value) {
        this.isNotWired = value;
    }

    /**
     * Gets the value of the callOnAspectTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getCallOnAspectTime() {
        return callOnAspectTime;
    }

    /**
     * Sets the value of the callOnAspectTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setCallOnAspectTime(Duration value) {
        this.callOnAspectTime = value;
    }

    /**
     * Gets the value of the sightDistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSightDistance() {
        return sightDistance;
    }

    /**
     * Sets the value of the sightDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSightDistance(BigDecimal value) {
        this.sightDistance = value;
    }

}
