//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * the tuple of references to the signal and its aspect plus the level of enforcement
 * 
 * <p>Java class for SignalAndGivenAspect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalAndGivenAspect"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}AssetAndGivenState"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="relatedSignalAndAspect" type="{https://www.railml.org/schemas/3.2}SignalAndAspect"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalAndGivenAspect", propOrder = {
    "relatedSignalAndAspect"
})
public class SignalAndGivenAspect
    extends AssetAndGivenState
{

    @XmlElement(required = true)
    protected SignalAndAspect relatedSignalAndAspect;

    /**
     * Gets the value of the relatedSignalAndAspect property.
     * 
     * @return
     *     possible object is
     *     {@link SignalAndAspect }
     *     
     */
    public SignalAndAspect getRelatedSignalAndAspect() {
        return relatedSignalAndAspect;
    }

    /**
     * Sets the value of the relatedSignalAndAspect property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalAndAspect }
     *     
     */
    public void setRelatedSignalAndAspect(SignalAndAspect value) {
        this.relatedSignalAndAspect = value;
    }

}
