//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * reference to any signal and its aspect inside or outside the restricted area required for use and/or protection
 * 
 * <p>Java class for SignalWithAspect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalWithAspect"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}EntityIL"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="givenAspect" type="{https://www.railml.org/schemas/3.2}SignalAndGivenAspect"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="protectingSide" type="{https://www.railml.org/schemas/3.2}tProtectingSideList" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalWithAspect", propOrder = {
    "givenAspect"
})
public class SignalWithAspect
    extends EntityIL
{

    @XmlElement(required = true)
    protected SignalAndGivenAspect givenAspect;
    @XmlAttribute(name = "protectingSide")
    protected TProtectingSideList protectingSide;

    /**
     * Gets the value of the givenAspect property.
     * 
     * @return
     *     possible object is
     *     {@link SignalAndGivenAspect }
     *     
     */
    public SignalAndGivenAspect getGivenAspect() {
        return givenAspect;
    }

    /**
     * Sets the value of the givenAspect property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalAndGivenAspect }
     *     
     */
    public void setGivenAspect(SignalAndGivenAspect value) {
        this.givenAspect = value;
    }

    /**
     * Gets the value of the protectingSide property.
     * 
     * @return
     *     possible object is
     *     {@link TProtectingSideList }
     *     
     */
    public TProtectingSideList getProtectingSide() {
        return protectingSide;
    }

    /**
     * Sets the value of the protectingSide property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProtectingSideList }
     *     
     */
    public void setProtectingSide(TProtectingSideList value) {
        this.protectingSide = value;
    }

}
