//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeedProfileTrainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeedProfileTrainType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="etcsSpeedProfile" type="{https://www.railml.org/schemas/3.2}SpeedProfileEtcs" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="etcsTrainCategoryNumber" type="{https://www.railml.org/schemas/3.2}tEtcsTrainCategoryNumber" /&gt;
 *       &lt;attribute name="type" type="{https://www.railml.org/schemas/3.2}tTrainTypeExt" /&gt;
 *       &lt;attribute name="cantDeficiency" type="{https://www.railml.org/schemas/3.2}tCantDeficiency" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedProfileTrainType", propOrder = {
    "etcsSpeedProfile"
})
public class SpeedProfileTrainType {

    protected SpeedProfileEtcs etcsSpeedProfile;
    @XmlAttribute(name = "etcsTrainCategoryNumber")
    protected Integer etcsTrainCategoryNumber;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "cantDeficiency")
    protected Integer cantDeficiency;

    /**
     * Gets the value of the etcsSpeedProfile property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedProfileEtcs }
     *     
     */
    public SpeedProfileEtcs getEtcsSpeedProfile() {
        return etcsSpeedProfile;
    }

    /**
     * Sets the value of the etcsSpeedProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedProfileEtcs }
     *     
     */
    public void setEtcsSpeedProfile(SpeedProfileEtcs value) {
        this.etcsSpeedProfile = value;
    }

    /**
     * Gets the value of the etcsTrainCategoryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEtcsTrainCategoryNumber() {
        return etcsTrainCategoryNumber;
    }

    /**
     * Sets the value of the etcsTrainCategoryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEtcsTrainCategoryNumber(Integer value) {
        this.etcsTrainCategoryNumber = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the cantDeficiency property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCantDeficiency() {
        return cantDeficiency;
    }

    /**
     * Sets the value of the cantDeficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCantDeficiency(Integer value) {
        this.cantDeficiency = value;
    }

}
