//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeedSection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeedSection"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}FunctionalInfrastructureEntity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="validForSpeedProfile" type="{https://www.railml.org/schemas/3.2}tElementWithIDref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="maxSpeed" type="{https://www.railml.org/schemas/3.2}tVMax" /&gt;
 *       &lt;attribute name="isTemporary" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="isSignalized" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="refersToTrain" type="{https://www.railml.org/schemas/3.2}tTrainRelation" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedSection", propOrder = {
    "validForSpeedProfile"
})
public class SpeedSection
    extends FunctionalInfrastructureEntity
{

    protected List<TElementWithIDref> validForSpeedProfile;
    @XmlAttribute(name = "maxSpeed")
    protected String maxSpeed;
    @XmlAttribute(name = "isTemporary")
    protected Boolean isTemporary;
    @XmlAttribute(name = "isSignalized")
    protected Boolean isSignalized;
    @XmlAttribute(name = "refersToTrain")
    protected TTrainRelation refersToTrain;

    /**
     * Gets the value of the validForSpeedProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the validForSpeedProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidForSpeedProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TElementWithIDref }
     * 
     * 
     */
    public List<TElementWithIDref> getValidForSpeedProfile() {
        if (validForSpeedProfile == null) {
            validForSpeedProfile = new ArrayList<TElementWithIDref>();
        }
        return this.validForSpeedProfile;
    }

    /**
     * Gets the value of the maxSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxSpeed() {
        return maxSpeed;
    }

    /**
     * Sets the value of the maxSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxSpeed(String value) {
        this.maxSpeed = value;
    }

    /**
     * Gets the value of the isTemporary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTemporary() {
        return isTemporary;
    }

    /**
     * Sets the value of the isTemporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTemporary(Boolean value) {
        this.isTemporary = value;
    }

    /**
     * Gets the value of the isSignalized property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSignalized() {
        return isSignalized;
    }

    /**
     * Sets the value of the isSignalized property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSignalized(Boolean value) {
        this.isSignalized = value;
    }

    /**
     * Gets the value of the refersToTrain property.
     * 
     * @return
     *     possible object is
     *     {@link TTrainRelation }
     *     
     */
    public TTrainRelation getRefersToTrain() {
        return refersToTrain;
    }

    /**
     * Sets the value of the refersToTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrainRelation }
     *     
     */
    public void setRefersToTrain(TTrainRelation value) {
        this.refersToTrain = value;
    }

}
