//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeedProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeedProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.railml.org/schemas/3.2}tElementWithIDandName"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tilting" type="{https://www.railml.org/schemas/3.2}SpeedProfileTilting" minOccurs="0"/&gt;
 *         &lt;element name="load" type="{https://www.railml.org/schemas/3.2}SpeedProfileLoad" minOccurs="0"/&gt;
 *         &lt;element name="braking" type="{https://www.railml.org/schemas/3.2}SpeedProfileBraking" minOccurs="0"/&gt;
 *         &lt;element name="trainType" type="{https://www.railml.org/schemas/3.2}SpeedProfileTrainType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{https://www.railml.org/schemas/3.2}aSpeedProfile"/&gt;
 *       &lt;attribute name="isBasicSpeedProfile" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="mVersion" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedProfile", propOrder = {
    "tilting",
    "load",
    "braking",
    "trainType"
})
public class SpeedProfile
    extends TElementWithIDandName
{

    protected SpeedProfileTilting tilting;
    protected SpeedProfileLoad load;
    protected SpeedProfileBraking braking;
    protected List<SpeedProfileTrainType> trainType;
    @XmlAttribute(name = "isBasicSpeedProfile")
    protected Boolean isBasicSpeedProfile;
    @XmlAttribute(name = "mVersion")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger mVersion;
    @XmlAttribute(name = "influence")
    protected TSpeedProfileInfluence influence;
    @XmlAttribute(name = "maxCantDeficiency")
    protected Integer maxCantDeficiency;

    /**
     * Gets the value of the tilting property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedProfileTilting }
     *     
     */
    public SpeedProfileTilting getTilting() {
        return tilting;
    }

    /**
     * Sets the value of the tilting property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedProfileTilting }
     *     
     */
    public void setTilting(SpeedProfileTilting value) {
        this.tilting = value;
    }

    /**
     * Gets the value of the load property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedProfileLoad }
     *     
     */
    public SpeedProfileLoad getLoad() {
        return load;
    }

    /**
     * Sets the value of the load property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedProfileLoad }
     *     
     */
    public void setLoad(SpeedProfileLoad value) {
        this.load = value;
    }

    /**
     * Gets the value of the braking property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedProfileBraking }
     *     
     */
    public SpeedProfileBraking getBraking() {
        return braking;
    }

    /**
     * Sets the value of the braking property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedProfileBraking }
     *     
     */
    public void setBraking(SpeedProfileBraking value) {
        this.braking = value;
    }

    /**
     * Gets the value of the trainType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the trainType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpeedProfileTrainType }
     * 
     * 
     */
    public List<SpeedProfileTrainType> getTrainType() {
        if (trainType == null) {
            trainType = new ArrayList<SpeedProfileTrainType>();
        }
        return this.trainType;
    }

    /**
     * Gets the value of the isBasicSpeedProfile property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBasicSpeedProfile() {
        return isBasicSpeedProfile;
    }

    /**
     * Sets the value of the isBasicSpeedProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBasicSpeedProfile(Boolean value) {
        this.isBasicSpeedProfile = value;
    }

    /**
     * Gets the value of the mVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMVersion() {
        return mVersion;
    }

    /**
     * Sets the value of the mVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMVersion(BigInteger value) {
        this.mVersion = value;
    }

    /**
     * Gets the value of the influence property.
     * 
     * @return
     *     possible object is
     *     {@link TSpeedProfileInfluence }
     *     
     */
    public TSpeedProfileInfluence getInfluence() {
        return influence;
    }

    /**
     * Sets the value of the influence property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSpeedProfileInfluence }
     *     
     */
    public void setInfluence(TSpeedProfileInfluence value) {
        this.influence = value;
    }

    /**
     * Gets the value of the maxCantDeficiency property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxCantDeficiency() {
        return maxCantDeficiency;
    }

    /**
     * Sets the value of the maxCantDeficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxCantDeficiency(Integer value) {
        this.maxCantDeficiency = value;
    }

}
