//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tContactStripMaterial.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="tContactStripMaterial"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="carbonAdditiveMaterial"/&gt;
 *     &lt;enumeration value="carbonCladdedCopper"/&gt;
 *     &lt;enumeration value="copper"/&gt;
 *     &lt;enumeration value="copperAlloy"/&gt;
 *     &lt;enumeration value="copperCladCarbon"/&gt;
 *     &lt;enumeration value="copperSteel"/&gt;
 *     &lt;enumeration value="impregnatedCarbon"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *     &lt;enumeration value="plainCarbon"/&gt;
 *     &lt;enumeration value="sinteredCopper"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tContactStripMaterial")
@XmlEnum
public enum TContactStripMaterial {

    @XmlEnumValue("carbonAdditiveMaterial")
    CARBON_ADDITIVE_MATERIAL("carbonAdditiveMaterial"),
    @XmlEnumValue("carbonCladdedCopper")
    CARBON_CLADDED_COPPER("carbonCladdedCopper"),
    @XmlEnumValue("copper")
    COPPER("copper"),
    @XmlEnumValue("copperAlloy")
    COPPER_ALLOY("copperAlloy"),
    @XmlEnumValue("copperCladCarbon")
    COPPER_CLAD_CARBON("copperCladCarbon"),
    @XmlEnumValue("copperSteel")
    COPPER_STEEL("copperSteel"),
    @XmlEnumValue("impregnatedCarbon")
    IMPREGNATED_CARBON("impregnatedCarbon"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("plainCarbon")
    PLAIN_CARBON("plainCarbon"),
    @XmlEnumValue("sinteredCopper")
    SINTERED_COPPER("sinteredCopper");
    private final String value;

    TContactStripMaterial(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TContactStripMaterial fromValue(String v) {
        for (TContactStripMaterial c: TContactStripMaterial.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
