//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDerailingPosition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="tDerailingPosition"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="derailingPosition"/&gt;
 *     &lt;enumeration value="passablePosition"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tDerailingPosition")
@XmlEnum
public enum TDerailingPosition {

    @XmlEnumValue("derailingPosition")
    DERAILING_POSITION("derailingPosition"),
    @XmlEnumValue("passablePosition")
    PASSABLE_POSITION("passablePosition");
    private final String value;

    TDerailingPosition(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TDerailingPosition fromValue(String v) {
        for (TDerailingPosition c: TDerailingPosition.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
