//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDescriptionLevel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="tDescriptionLevel"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Macro"/&gt;
 *     &lt;enumeration value="Meso"/&gt;
 *     &lt;enumeration value="Micro"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tDescriptionLevel")
@XmlEnum
public enum TDescriptionLevel {

    @XmlEnumValue("Macro")
    MACRO("Macro"),
    @XmlEnumValue("Meso")
    MESO("Meso"),
    @XmlEnumValue("Micro")
    MICRO("Micro");
    private final String value;

    TDescriptionLevel(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TDescriptionLevel fromValue(String v) {
        for (TDescriptionLevel c: TDescriptionLevel.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
