//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDetectorMedium.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="tDetectorMedium"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="hydraulic"/&gt;
 *     &lt;enumeration value="inductive"/&gt;
 *     &lt;enumeration value="magnetic"/&gt;
 *     &lt;enumeration value="mechanical"/&gt;
 *     &lt;enumeration value="optical"/&gt;
 *     &lt;enumeration value="pneumatic"/&gt;
 *     &lt;enumeration value="radio"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tDetectorMedium")
@XmlEnum
public enum TDetectorMedium {

    @XmlEnumValue("hydraulic")
    HYDRAULIC("hydraulic"),
    @XmlEnumValue("inductive")
    INDUCTIVE("inductive"),
    @XmlEnumValue("magnetic")
    MAGNETIC("magnetic"),
    @XmlEnumValue("mechanical")
    MECHANICAL("mechanical"),
    @XmlEnumValue("optical")
    OPTICAL("optical"),
    @XmlEnumValue("pneumatic")
    PNEUMATIC("pneumatic"),
    @XmlEnumValue("radio")
    RADIO("radio");
    private final String value;

    TDetectorMedium(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TDetectorMedium fromValue(String v) {
        for (TDetectorMedium c: TDetectorMedium.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
