//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimesScope.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TimesScope"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="commercial"/&gt;
 *     &lt;enumeration value="operational"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TimesScope")
@XmlEnum
public enum TimesScope {


    /**
     * Commercial time (german: verkehrliche Zeit) - If changed the change needs to be communicated as such. This information is intended and relevant for transportation customers/passengers.
     * 
     */
    @XmlEnumValue("commercial")
    COMMERCIAL("commercial"),

    /**
     * Operational time (german: betriebliche Zeit) - This information is intended and relevant for RU/IM operations.
     * 
     */
    @XmlEnumValue("operational")
    OPERATIONAL("operational");
    private final String value;

    TimesScope(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimesScope fromValue(String v) {
        for (TimesScope c: TimesScope.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
