//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOverlapReleaseCondition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="tOverlapReleaseCondition"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="startTimerAfterVacating"/&gt;
 *     &lt;enumeration value="startTimerUponOccupation"/&gt;
 *     &lt;enumeration value="trainInitiatedTrigger"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tOverlapReleaseCondition")
@XmlEnum
public enum TOverlapReleaseCondition {

    @XmlEnumValue("startTimerAfterVacating")
    START_TIMER_AFTER_VACATING("startTimerAfterVacating"),
    @XmlEnumValue("startTimerUponOccupation")
    START_TIMER_UPON_OCCUPATION("startTimerUponOccupation"),
    @XmlEnumValue("trainInitiatedTrigger")
    TRAIN_INITIATED_TRIGGER("trainInitiatedTrigger");
    private final String value;

    TOverlapReleaseCondition(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TOverlapReleaseCondition fromValue(String v) {
        for (TOverlapReleaseCondition c: TOverlapReleaseCondition.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
