//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 12:29:34 PM EEST 
//


package com.aorkado.railml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransportServiceReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportServiceReference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="direction" type="{https://www.railml.org/schemas/3.2}Direction" /&gt;
 *       &lt;attribute name="ref" use="required" type="{https://www.railml.org/schemas/3.2}tRef" /&gt;
 *       &lt;attribute name="fromDescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="toDescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportServiceReference")
public class TransportServiceReference {

    @XmlAttribute(name = "direction")
    protected Direction direction;
    @XmlAttribute(name = "ref", required = true)
    protected String ref;
    @XmlAttribute(name = "fromDescription")
    protected String fromDescription;
    @XmlAttribute(name = "toDescription")
    protected String toDescription;

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link Direction }
     *     
     */
    public Direction getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Direction }
     *     
     */
    public void setDirection(Direction value) {
        this.direction = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the fromDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromDescription() {
        return fromDescription;
    }

    /**
     * Sets the value of the fromDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDescription(String value) {
        this.fromDescription = value;
    }

    /**
     * Gets the value of the toDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToDescription() {
        return toDescription;
    }

    /**
     * Sets the value of the toDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToDescription(String value) {
        this.toDescription = value;
    }

}
